/**
 * Curated VS Code theme preset sets.
 *
 * Each set contains both a dark and light variant so the active color scheme
 * automatically follows the user's light / dark / system preference.
 *
 * The `colors` objects are minimal VS Code–compatible JSON containing only the
 * keys that `VSCODE_TO_CSS_MAP` (in vscode-theme-parser.ts) maps to CSS
 * variables, plus terminal ANSI colors for a complete experience.
 */

export interface ThemeJSON {
  name: string;
  type: 'dark' | 'light';
  colors: Record<string, string>;
  tokenColors?: Array<{
    scope?: string | string[];
    settings: { foreground?: string; fontStyle?: string };
  }>;
}

export interface ThemePresetSet {
  /** Stable identifier persisted to localStorage */
  id: string;
  /** Human-readable label shown in the picker */
  label: string;
  /** Four hex preview colors for the dark variant: [bg, fg, accent, secondary] */
  previewColors: { dark: [string, string, string, string]; light: [string, string, string, string] };
  /** Dark variant theme JSON */
  dark: ThemeJSON;
  /** Light variant theme JSON */
  light: ThemeJSON;
}

export const themePresets: ThemePresetSet[] = [
  // {
  //   id: 'catppuccin',
  //   label: 'Catppuccin',
  //   previewColors: {
  //     dark: ['#1e1e2e', '#cdd6f4', '#cba6f7', '#f5c2e7'],
  //     light: ['#eff1f5', '#4c4f69', '#8839ef', '#ea76cb'],
  //   },
  //   dark: {
  //     name: 'Catppuccin Mocha',
  //     type: 'dark',
  //     colors: {
  //       'editor.background': '#1e1e2e',
  //       'editor.foreground': '#cdd6f4',
  //       'sideBar.background': '#181825',
  //       'sideBar.foreground': '#cdd6f4',
  //       'editorWidget.background': '#1e1e2e',
  //       'editorWidget.foreground': '#cdd6f4',
  //       'dropdown.background': '#1e1e2e',
  //       'dropdown.foreground': '#cdd6f4',
  //       'focusBorder': '#cba6f7',
  //       'input.background': '#181825',
  //       'panel.border': '#313244',
  //       'button.background': '#cba6f7',
  //       'button.foreground': '#1e1e2e',
  //       'badge.background': '#cba6f7',
  //       'badge.foreground': '#1e1e2e',
  //       'list.activeSelectionBackground': '#313244',
  //       'list.activeSelectionForeground': '#cdd6f4',
  //       'tab.inactiveBackground': '#181825',
  //       'descriptionForeground': '#a6adc8',
  //       'errorForeground': '#f38ba8',
  //       'terminal.background': '#1e1e2e',
  //       'terminal.foreground': '#cdd6f4',
  //       'terminal.ansiBlack': '#45475a',
  //       'terminal.ansiRed': '#f38ba8',
  //       'terminal.ansiGreen': '#a6e3a1',
  //       'terminal.ansiYellow': '#f9e2af',
  //       'terminal.ansiBlue': '#89b4fa',
  //       'terminal.ansiMagenta': '#cba6f7',
  //       'terminal.ansiCyan': '#94e2d5',
  //       'terminal.ansiWhite': '#bac2de',
  //     },
  //   },
  //   light: {
  //     name: 'Catppuccin Latte',
  //     type: 'light',
  //     colors: {
  //       'editor.background': '#eff1f5',
  //       'editor.foreground': '#4c4f69',
  //       'sideBar.background': '#e6e9ef',
  //       'sideBar.foreground': '#4c4f69',
  //       'editorWidget.background': '#eff1f5',
  //       'editorWidget.foreground': '#4c4f69',
  //       'dropdown.background': '#eff1f5',
  //       'dropdown.foreground': '#4c4f69',
  //       'focusBorder': '#8839ef',
  //       'input.background': '#e6e9ef',
  //       'panel.border': '#ccd0da',
  //       'button.background': '#8839ef',
  //       'button.foreground': '#eff1f5',
  //       'badge.background': '#8839ef',
  //       'badge.foreground': '#eff1f5',
  //       'list.activeSelectionBackground': '#ccd0da',
  //       'list.activeSelectionForeground': '#4c4f69',
  //       'tab.inactiveBackground': '#e6e9ef',
  //       'descriptionForeground': '#8c8fa1',
  //       'errorForeground': '#d20f39',
  //       'terminal.background': '#eff1f5',
  //       'terminal.foreground': '#4c4f69',
  //       'terminal.ansiBlack': '#5c5f77',
  //       'terminal.ansiRed': '#d20f39',
  //       'terminal.ansiGreen': '#40a02b',
  //       'terminal.ansiYellow': '#df8e1d',
  //       'terminal.ansiBlue': '#1e66f5',
  //       'terminal.ansiMagenta': '#8839ef',
  //       'terminal.ansiCyan': '#179299',
  //       'terminal.ansiWhite': '#acb0be',
  //     },
  //   },
  // },
  {
    id: 'dracula',
    label: 'Dracula',
    previewColors: {
      dark: ['#282a36', '#f8f8f2', '#bd93f9', '#ff79c6'],
      light: ['#f8f8f2', '#282a36', '#9580ff', '#ff80bf'],
    },
    dark: {
      name: 'Dracula',
      type: 'dark',
      colors: {
        'editor.background': '#282a36',
        'editor.foreground': '#f8f8f2',
        'sideBar.background': '#21222c',
        'sideBar.foreground': '#f8f8f2',
        'editorWidget.background': '#282a36',
        'editorWidget.foreground': '#f8f8f2',
        'dropdown.background': '#282a36',
        'dropdown.foreground': '#f8f8f2',
        'focusBorder': '#6272a4',
        'input.background': '#21222c',
        'panel.border': '#44475a',
        'button.background': '#bd93f9',
        'button.foreground': '#282a36',
        'badge.background': '#bd93f9',
        'badge.foreground': '#282a36',
        'list.activeSelectionBackground': '#44475a',
        'list.activeSelectionForeground': '#f8f8f2',
        'tab.inactiveBackground': '#21222c',
        'descriptionForeground': '#6272a4',
        'errorForeground': '#ff5555',
        'terminal.background': '#282a36',
        'terminal.foreground': '#f8f8f2',
        'terminal.ansiBlack': '#21222c',
        'terminal.ansiRed': '#ff5555',
        'terminal.ansiGreen': '#50fa7b',
        'terminal.ansiYellow': '#f1fa8c',
        'terminal.ansiBlue': '#bd93f9',
        'terminal.ansiMagenta': '#ff79c6',
        'terminal.ansiCyan': '#8be9fd',
        'terminal.ansiWhite': '#f8f8f2',
      },
    },
    light: {
      name: 'Dracula Light',
      type: 'light',
      colors: {
        'editor.background': '#f8f8f2',
        'editor.foreground': '#282a36',
        'sideBar.background': '#eaeaeb',
        'sideBar.foreground': '#282a36',
        'editorWidget.background': '#f8f8f2',
        'editorWidget.foreground': '#282a36',
        'dropdown.background': '#f8f8f2',
        'dropdown.foreground': '#282a36',
        'focusBorder': '#9580ff',
        'input.background': '#eaeaeb',
        'panel.border': '#d4d4d6',
        'button.background': '#9580ff',
        'button.foreground': '#f8f8f2',
        'badge.background': '#9580ff',
        'badge.foreground': '#f8f8f2',
        'list.activeSelectionBackground': '#d4d4d6',
        'list.activeSelectionForeground': '#282a36',
        'tab.inactiveBackground': '#eaeaeb',
        'descriptionForeground': '#6272a4',
        'errorForeground': '#ff5555',
        'terminal.background': '#f8f8f2',
        'terminal.foreground': '#282a36',
        'terminal.ansiBlack': '#282a36',
        'terminal.ansiRed': '#e13535',
        'terminal.ansiGreen': '#2a9f4a',
        'terminal.ansiYellow': '#c4a000',
        'terminal.ansiBlue': '#7c6dd8',
        'terminal.ansiMagenta': '#e06cb0',
        'terminal.ansiCyan': '#2aacbd',
        'terminal.ansiWhite': '#f8f8f2',
      },
    },
  },
  // {
  //   id: 'one',
  //   label: 'One',
  //   previewColors: {
  //     dark: ['#282c34', '#abb2bf', '#61afef', '#c678dd'],
  //     light: ['#fafafa', '#383a42', '#4078f2', '#a626a4'],
  //   },
  //   dark: {
  //     name: 'One Dark Pro',
  //     type: 'dark',
  //     colors: {
  //       'editor.background': '#282c34',
  //       'editor.foreground': '#abb2bf',
  //       'sideBar.background': '#21252b',
  //       'sideBar.foreground': '#abb2bf',
  //       'editorWidget.background': '#282c34',
  //       'editorWidget.foreground': '#abb2bf',
  //       'dropdown.background': '#282c34',
  //       'dropdown.foreground': '#abb2bf',
  //       'focusBorder': '#528bff',
  //       'input.background': '#1d1f23',
  //       'panel.border': '#3e4452',
  //       'button.background': '#61afef',
  //       'button.foreground': '#282c34',
  //       'badge.background': '#61afef',
  //       'badge.foreground': '#282c34',
  //       'list.activeSelectionBackground': '#2c313a',
  //       'list.activeSelectionForeground': '#abb2bf',
  //       'tab.inactiveBackground': '#21252b',
  //       'descriptionForeground': '#636b78',
  //       'errorForeground': '#e06c75',
  //       'terminal.background': '#282c34',
  //       'terminal.foreground': '#abb2bf',
  //       'terminal.ansiBlack': '#3f4451',
  //       'terminal.ansiRed': '#e06c75',
  //       'terminal.ansiGreen': '#98c379',
  //       'terminal.ansiYellow': '#e5c07b',
  //       'terminal.ansiBlue': '#61afef',
  //       'terminal.ansiMagenta': '#c678dd',
  //       'terminal.ansiCyan': '#56b6c2',
  //       'terminal.ansiWhite': '#abb2bf',
  //     },
  //   },
  //   light: {
  //     name: 'One Light',
  //     type: 'light',
  //     colors: {
  //       'editor.background': '#fafafa',
  //       'editor.foreground': '#383a42',
  //       'sideBar.background': '#eaeaeb',
  //       'sideBar.foreground': '#383a42',
  //       'editorWidget.background': '#fafafa',
  //       'editorWidget.foreground': '#383a42',
  //       'dropdown.background': '#fafafa',
  //       'dropdown.foreground': '#383a42',
  //       'focusBorder': '#526fff',
  //       'input.background': '#eaeaeb',
  //       'panel.border': '#dbdbdc',
  //       'button.background': '#4078f2',
  //       'button.foreground': '#fafafa',
  //       'badge.background': '#4078f2',
  //       'badge.foreground': '#fafafa',
  //       'list.activeSelectionBackground': '#dbdbdc',
  //       'list.activeSelectionForeground': '#383a42',
  //       'tab.inactiveBackground': '#eaeaeb',
  //       'descriptionForeground': '#a0a1a7',
  //       'errorForeground': '#e45649',
  //       'terminal.background': '#fafafa',
  //       'terminal.foreground': '#383a42',
  //       'terminal.ansiBlack': '#383a42',
  //       'terminal.ansiRed': '#e45649',
  //       'terminal.ansiGreen': '#50a14f',
  //       'terminal.ansiYellow': '#c18401',
  //       'terminal.ansiBlue': '#4078f2',
  //       'terminal.ansiMagenta': '#a626a4',
  //       'terminal.ansiCyan': '#0184bc',
  //       'terminal.ansiWhite': '#a0a1a7',
  //     },
  //   },
  // },
  {
    id: 'nord',
    label: 'Nord',
    previewColors: {
      dark: ['#2e3440', '#d8dee9', '#88c0d0', '#81a1c1'],
      light: ['#eceff4', '#2e3440', '#5e81ac', '#88c0d0'],
    },
    dark: {
      name: 'Nord',
      type: 'dark',
      colors: {
        'editor.background': '#2e3440',
        'editor.foreground': '#d8dee9',
        'sideBar.background': '#1b2029',
        'sideBar.foreground': '#d8dee9',
        'editorWidget.background': '#2e3440',
        'editorWidget.foreground': '#d8dee9',
        'dropdown.background': '#3b4252',
        'dropdown.foreground': '#d8dee9',
        'focusBorder': '#88c0d0',
        'input.background': '#3b4252',
        'panel.border': '#3b4252',
        'button.background': '#88c0d0',
        'button.foreground': '#2e3440',
        'badge.background': '#88c0d0',
        'badge.foreground': '#2e3440',
        'list.activeSelectionBackground': '#3b4252',
        'list.activeSelectionForeground': '#d8dee9',
        'tab.inactiveBackground': '#2e3440',
        'descriptionForeground': '#7b88a1',
        'errorForeground': '#bf616a',
        'terminal.background': '#2e3440',
        'terminal.foreground': '#d8dee9',
        'terminal.ansiBlack': '#3b4252',
        'terminal.ansiRed': '#bf616a',
        'terminal.ansiGreen': '#a3be8c',
        'terminal.ansiYellow': '#ebcb8b',
        'terminal.ansiBlue': '#81a1c1',
        'terminal.ansiMagenta': '#b48ead',
        'terminal.ansiCyan': '#88c0d0',
        'terminal.ansiWhite': '#e5e9f0',
      },
    },
    light: {
      name: 'Nord Light',
      type: 'light',
      colors: {
        'editor.background': '#eceff4',
        'editor.foreground': '#2e3440',
        'sideBar.background': '#e5e9f0',
        'sideBar.foreground': '#2e3440',
        'editorWidget.background': '#eceff4',
        'editorWidget.foreground': '#2e3440',
        'dropdown.background': '#eceff4',
        'dropdown.foreground': '#2e3440',
        'focusBorder': '#5e81ac',
        'input.background': '#e5e9f0',
        'panel.border': '#d8dee9',
        'button.background': '#5e81ac',
        'button.foreground': '#eceff4',
        'badge.background': '#5e81ac',
        'badge.foreground': '#eceff4',
        'list.activeSelectionBackground': '#d8dee9',
        'list.activeSelectionForeground': '#2e3440',
        'tab.inactiveBackground': '#e5e9f0',
        'descriptionForeground': '#7b88a1',
        'errorForeground': '#bf616a',
        'terminal.background': '#eceff4',
        'terminal.foreground': '#2e3440',
        'terminal.ansiBlack': '#2e3440',
        'terminal.ansiRed': '#bf616a',
        'terminal.ansiGreen': '#a3be8c',
        'terminal.ansiYellow': '#d08770',
        'terminal.ansiBlue': '#5e81ac',
        'terminal.ansiMagenta': '#b48ead',
        'terminal.ansiCyan': '#88c0d0',
        'terminal.ansiWhite': '#e5e9f0',
      },
    },
  },
  {
    id: 'rose-pine',
    label: 'Rosé Pine',
    previewColors: {
      dark: ['#191724', '#e0def4', '#c4a7e7', '#ebbcba'],
      light: ['#faf4ed', '#575279', '#907aa9', '#d7827e'],
    },
    dark: {
      name: 'Rosé Pine',
      type: 'dark',
      colors: {
        'editor.background': '#191724',
        'editor.foreground': '#e0def4',
        'sideBar.background': '#1f1d2e',
        'sideBar.foreground': '#e0def4',
        'editorWidget.background': '#191724',
        'editorWidget.foreground': '#e0def4',
        'dropdown.background': '#1f1d2e',
        'dropdown.foreground': '#e0def4',
        'focusBorder': '#c4a7e7',
        'input.background': '#1f1d2e',
        'panel.border': '#26233a',
        'button.background': '#c4a7e7',
        'button.foreground': '#191724',
        'badge.background': '#c4a7e7',
        'badge.foreground': '#191724',
        'list.activeSelectionBackground': '#26233a',
        'list.activeSelectionForeground': '#e0def4',
        'tab.inactiveBackground': '#1f1d2e',
        'descriptionForeground': '#908caa',
        'errorForeground': '#eb6f92',
        'terminal.background': '#191724',
        'terminal.foreground': '#e0def4',
        'terminal.ansiBlack': '#26233a',
        'terminal.ansiRed': '#eb6f92',
        'terminal.ansiGreen': '#9ccfd8',
        'terminal.ansiYellow': '#f6c177',
        'terminal.ansiBlue': '#31748f',
        'terminal.ansiMagenta': '#c4a7e7',
        'terminal.ansiCyan': '#9ccfd8',
        'terminal.ansiWhite': '#e0def4',
      },
    },
    light: {
      name: 'Rosé Pine Dawn',
      type: 'light',
      colors: {
        'editor.background': '#faf4ed',
        'editor.foreground': '#575279',
        'sideBar.background': '#f2e9e1',
        'sideBar.foreground': '#575279',
        'editorWidget.background': '#faf4ed',
        'editorWidget.foreground': '#575279',
        'dropdown.background': '#faf4ed',
        'dropdown.foreground': '#575279',
        'focusBorder': '#907aa9',
        'input.background': '#f2e9e1',
        'panel.border': '#dfdad9',
        'button.background': '#907aa9',
        'button.foreground': '#faf4ed',
        'badge.background': '#907aa9',
        'badge.foreground': '#faf4ed',
        'list.activeSelectionBackground': '#dfdad9',
        'list.activeSelectionForeground': '#575279',
        'tab.inactiveBackground': '#f2e9e1',
        'descriptionForeground': '#9893a5',
        'errorForeground': '#b4637a',
        'terminal.background': '#faf4ed',
        'terminal.foreground': '#575279',
        'terminal.ansiBlack': '#575279',
        'terminal.ansiRed': '#b4637a',
        'terminal.ansiGreen': '#56949f',
        'terminal.ansiYellow': '#ea9d34',
        'terminal.ansiBlue': '#286983',
        'terminal.ansiMagenta': '#907aa9',
        'terminal.ansiCyan': '#56949f',
        'terminal.ansiWhite': '#f2e9e1',
      },
    },
  },

  {
    id: 'tokyo-night',
    label: 'Tokyo Night',
    previewColors: {
      dark: ['#1a1b26', '#a9b1d6', '#7aa2f7', '#bb9af7'],
      light: ['#d5d6db', '#343b58', '#34548a', '#5a4a78'],
    },
    dark: {
      name: 'Tokyo Night',
      type: 'dark',
      colors: {
        'editor.background': '#1a1b26',
        'editor.foreground': '#a9b1d6',
        'sideBar.background': '#1f2335',
        'sideBar.foreground': '#a9b1d6',
        'editorWidget.background': '#1a1b26',
        'editorWidget.foreground': '#a9b1d6',
        'dropdown.background': '#1f2335',
        'dropdown.foreground': '#a9b1d6',
        'focusBorder': '#7aa2f7',
        'input.background': '#1f2335',
        'panel.border': '#292e42',
        'button.background': '#7aa2f7',
        'button.foreground': '#1a1b26',
        'badge.background': '#7aa2f7',
        'badge.foreground': '#1a1b26',
        'list.activeSelectionBackground': '#292e42',
        'list.activeSelectionForeground': '#a9b1d6',
        'tab.inactiveBackground': '#1f2335',
        'descriptionForeground': '#565f89',
        'errorForeground': '#f7768e',
        'terminal.background': '#1a1b26',
        'terminal.foreground': '#a9b1d6',
        'terminal.ansiBlack': '#414868',
        'terminal.ansiRed': '#f7768e',
        'terminal.ansiGreen': '#9ece6a',
        'terminal.ansiYellow': '#e0af68',
        'terminal.ansiBlue': '#7aa2f7',
        'terminal.ansiMagenta': '#bb9af7',
        'terminal.ansiCyan': '#7dcfff',
        'terminal.ansiWhite': '#c0caf5',
      },
    },
    light: {
      name: 'Tokyo Night Light',
      type: 'light',
      colors: {
        'editor.background': '#d5d6db',
        'editor.foreground': '#343b58',
        'sideBar.background': '#cbccd1',
        'sideBar.foreground': '#343b58',
        'editorWidget.background': '#d5d6db',
        'editorWidget.foreground': '#343b58',
        'dropdown.background': '#d5d6db',
        'dropdown.foreground': '#343b58',
        'focusBorder': '#34548a',
        'input.background': '#cbccd1',
        'panel.border': '#c0c1c6',
        'button.background': '#34548a',
        'button.foreground': '#d5d6db',
        'badge.background': '#34548a',
        'badge.foreground': '#d5d6db',
        'list.activeSelectionBackground': '#c0c1c6',
        'list.activeSelectionForeground': '#343b58',
        'tab.inactiveBackground': '#cbccd1',
        'descriptionForeground': '#6a6e82',
        'errorForeground': '#8c4351',
        'terminal.background': '#d5d6db',
        'terminal.foreground': '#343b58',
        'terminal.ansiBlack': '#343b58',
        'terminal.ansiRed': '#8c4351',
        'terminal.ansiGreen': '#33635c',
        'terminal.ansiYellow': '#8f5e15',
        'terminal.ansiBlue': '#34548a',
        'terminal.ansiMagenta': '#5a4a78',
        'terminal.ansiCyan': '#0f4b6e',
        'terminal.ansiWhite': '#d5d6db',
      },
    },
  },
  // {
  //   id: 'gruvbox',
  //   label: 'Gruvbox',
  //   previewColors: {
  //     dark: ['#282828', '#ebdbb2', '#fabd2f', '#b8bb26'],
  //     light: ['#fbf1c7', '#3c3836', '#d79921', '#98971a'],
  //   },
  //   dark: {
  //     name: 'Gruvbox Dark',
  //     type: 'dark',
  //     colors: {
  //       'editor.background': '#282828',
  //       'editor.foreground': '#ebdbb2',
  //       'sideBar.background': '#1d2021',
  //       'sideBar.foreground': '#ebdbb2',
  //       'editorWidget.background': '#282828',
  //       'editorWidget.foreground': '#ebdbb2',
  //       'dropdown.background': '#282828',
  //       'dropdown.foreground': '#ebdbb2',
  //       'focusBorder': '#fabd2f',
  //       'input.background': '#1d2021',
  //       'panel.border': '#3c3836',
  //       'button.background': '#fabd2f',
  //       'button.foreground': '#282828',
  //       'badge.background': '#fabd2f',
  //       'badge.foreground': '#282828',
  //       'list.activeSelectionBackground': '#3c3836',
  //       'list.activeSelectionForeground': '#ebdbb2',
  //       'tab.inactiveBackground': '#1d2021',
  //       'descriptionForeground': '#a89984',
  //       'errorForeground': '#fb4934',
  //       'terminal.background': '#282828',
  //       'terminal.foreground': '#ebdbb2',
  //       'terminal.ansiBlack': '#3c3836',
  //       'terminal.ansiRed': '#fb4934',
  //       'terminal.ansiGreen': '#b8bb26',
  //       'terminal.ansiYellow': '#fabd2f',
  //       'terminal.ansiBlue': '#83a598',
  //       'terminal.ansiMagenta': '#d3869b',
  //       'terminal.ansiCyan': '#8ec07c',
  //       'terminal.ansiWhite': '#ebdbb2',
  //     },
  //   },
  //   light: {
  //     name: 'Gruvbox Light',
  //     type: 'light',
  //     colors: {
  //       'editor.background': '#fbf1c7',
  //       'editor.foreground': '#3c3836',
  //       'sideBar.background': '#f2e5bc',
  //       'sideBar.foreground': '#3c3836',
  //       'editorWidget.background': '#fbf1c7',
  //       'editorWidget.foreground': '#3c3836',
  //       'dropdown.background': '#fbf1c7',
  //       'dropdown.foreground': '#3c3836',
  //       'focusBorder': '#d79921',
  //       'input.background': '#f2e5bc',
  //       'panel.border': '#ebdbb2',
  //       'button.background': '#d79921',
  //       'button.foreground': '#fbf1c7',
  //       'badge.background': '#d79921',
  //       'badge.foreground': '#fbf1c7',
  //       'list.activeSelectionBackground': '#ebdbb2',
  //       'list.activeSelectionForeground': '#3c3836',
  //       'tab.inactiveBackground': '#f2e5bc',
  //       'descriptionForeground': '#7c6f64',
  //       'errorForeground': '#cc241d',
  //       'terminal.background': '#fbf1c7',
  //       'terminal.foreground': '#3c3836',
  //       'terminal.ansiBlack': '#3c3836',
  //       'terminal.ansiRed': '#cc241d',
  //       'terminal.ansiGreen': '#98971a',
  //       'terminal.ansiYellow': '#d79921',
  //       'terminal.ansiBlue': '#458588',
  //       'terminal.ansiMagenta': '#b16286',
  //       'terminal.ansiCyan': '#689d6a',
  //       'terminal.ansiWhite': '#fbf1c7',
  //     },
  //   },
  // },
  {
    id: 'solarized',
    label: 'Solarized',
    previewColors: {
      dark: ['#002b36', '#839496', '#268bd2', '#2aa198'],
      light: ['#fdf6e3', '#657b83', '#268bd2', '#2aa198'],
    },
    dark: {
      name: 'Solarized Dark',
      type: 'dark',
      colors: {
        'editor.background': '#002b36',
        'editor.foreground': '#839496',
        'sideBar.background': '#001e26',
        'sideBar.foreground': '#839496',
        'editorWidget.background': '#002b36',
        'editorWidget.foreground': '#839496',
        'dropdown.background': '#002b36',
        'dropdown.foreground': '#839496',
        'focusBorder': '#268bd2',
        'input.background': '#001e26',
        'panel.border': '#073642',
        'button.background': '#268bd2',
        'button.foreground': '#fdf6e3',
        'badge.background': '#268bd2',
        'badge.foreground': '#fdf6e3',
        'list.activeSelectionBackground': '#073642',
        'list.activeSelectionForeground': '#839496',
        'tab.inactiveBackground': '#001e26',
        'descriptionForeground': '#586e75',
        'errorForeground': '#dc322f',
        'terminal.background': '#002b36',
        'terminal.foreground': '#839496',
        'terminal.ansiBlack': '#073642',
        'terminal.ansiRed': '#dc322f',
        'terminal.ansiGreen': '#859900',
        'terminal.ansiYellow': '#b58900',
        'terminal.ansiBlue': '#268bd2',
        'terminal.ansiMagenta': '#d33682',
        'terminal.ansiCyan': '#2aa198',
        'terminal.ansiWhite': '#eee8d5',
      },
    },
    light: {
      name: 'Solarized Light',
      type: 'light',
      colors: {
        'editor.background': '#fdf6e3',
        'editor.foreground': '#657b83',
        'sideBar.background': '#EDE8D4',
        'sideBar.foreground': '#657b83',
        'editorWidget.background': '#fdf6e3',
        'editorWidget.foreground': '#657b83',
        'dropdown.background': '#fdf6e3',
        'dropdown.foreground': '#657b83',
        'focusBorder': '#268bd2',
        'input.background': '#eee8d5',
        'panel.border': '#eee8d5',
        'button.background': '#268bd2',
        'button.foreground': '#fdf6e3',
        'badge.background': '#268bd2',
        'badge.foreground': '#fdf6e3',
        'list.activeSelectionBackground': '#eee8d5',
        'list.activeSelectionForeground': '#657b83',
        'tab.inactiveBackground': '#eee8d5',
        'descriptionForeground': '#93a1a1',
        'errorForeground': '#dc322f',
        'terminal.background': '#fdf6e3',
        'terminal.foreground': '#657b83',
        'terminal.ansiBlack': '#073642',
        'terminal.ansiRed': '#dc322f',
        'terminal.ansiGreen': '#859900',
        'terminal.ansiYellow': '#b58900',
        'terminal.ansiBlue': '#268bd2',
        'terminal.ansiMagenta': '#d33682',
        'terminal.ansiCyan': '#2aa198',
        'terminal.ansiWhite': '#eee8d5',
      },
    },
  },
  {
    id: 'github',
    label: 'GitHub',
    previewColors: {
      dark: ['#0d1117', '#e6edf3', '#58a6ff', '#bc8cff'],
      light: ['#ffffff', '#24292f', '#0969da', '#8250df'],
    },
    dark: {
      name: 'GitHub Dark',
      type: 'dark',
      colors: {
        'editor.background': '#0d1117',
        'editor.foreground': '#e6edf3',
        'sideBar.background': '#010409',
        'sideBar.foreground': '#e6edf3',
        'editorWidget.background': '#0d1117',
        'editorWidget.foreground': '#e6edf3',
        'dropdown.background': '#0d1117',
        'dropdown.foreground': '#e6edf3',
        'focusBorder': '#58a6ff',
        'input.background': '#010409',
        'panel.border': '#21262d',
        'button.background': '#58a6ff',
        'button.foreground': '#0d1117',
        'badge.background': '#58a6ff',
        'badge.foreground': '#0d1117',
        'list.activeSelectionBackground': '#21262d',
        'list.activeSelectionForeground': '#e6edf3',
        'tab.inactiveBackground': '#010409',
        'descriptionForeground': '#8b949e',
        'errorForeground': '#f85149',
        'terminal.background': '#0d1117',
        'terminal.foreground': '#e6edf3',
        'terminal.ansiBlack': '#484f58',
        'terminal.ansiRed': '#ff7b72',
        'terminal.ansiGreen': '#3fb950',
        'terminal.ansiYellow': '#d29922',
        'terminal.ansiBlue': '#58a6ff',
        'terminal.ansiMagenta': '#bc8cff',
        'terminal.ansiCyan': '#39d2c0',
        'terminal.ansiWhite': '#b1bac4',
      },
    },
    light: {
      name: 'GitHub Light',
      type: 'light',
      colors: {
        'editor.background': '#ffffff',
        'editor.foreground': '#24292f',
        'sideBar.background': '#f6f8fa',
        'sideBar.foreground': '#24292f',
        'editorWidget.background': '#ffffff',
        'editorWidget.foreground': '#24292f',
        'dropdown.background': '#ffffff',
        'dropdown.foreground': '#24292f',
        'focusBorder': '#0969da',
        'input.background': '#f6f8fa',
        'panel.border': '#d0d7de',
        'button.background': '#0969da',
        'button.foreground': '#ffffff',
        'badge.background': '#0969da',
        'badge.foreground': '#ffffff',
        'list.activeSelectionBackground': '#ddf4ff',
        'list.activeSelectionForeground': '#24292f',
        'tab.inactiveBackground': '#f6f8fa',
        'descriptionForeground': '#57606a',
        'errorForeground': '#cf222e',
        'terminal.background': '#ffffff',
        'terminal.foreground': '#24292f',
        'terminal.ansiBlack': '#24292f',
        'terminal.ansiRed': '#cf222e',
        'terminal.ansiGreen': '#116329',
        'terminal.ansiYellow': '#4d2d00',
        'terminal.ansiBlue': '#0969da',
        'terminal.ansiMagenta': '#8250df',
        'terminal.ansiCyan': '#1b7c83',
        'terminal.ansiWhite': '#6e7781',
      },
    },
  },
];
