import { parseUiComponentMetadata } from '../component-metadata';
import { tooltipFixtures } from './tooltip.fixtures';

export const tooltipMetadata = parseUiComponentMetadata({
  id: 'tooltip',
  source: 'src/lib/components/ui/tooltip/index.ts',
  publicImport: '$lib/components/ui/tooltip',
  legacyImports: [
    '$lib/components/ui/tooltip/LinkTooltip.svelte',
    '$lib/components/ui/tooltip/Tooltip.svelte',
    '$lib/components/ui/tooltip/TooltipRich.svelte',
    '$lib/components/ui/tooltip/index.js',
    '$lib/components/ui/tooltip/link-tooltip-state.svelte',
  ],
  exports: [
    'Content',
    'LinkTooltip',
    'Portal',
    'Provider',
    'Root',
    'Tooltip',
    'TooltipContent',
    'TooltipPortal',
    'TooltipProvider',
    'TooltipRich',
    'TooltipRoot',
    'TooltipShortcut',
    'TooltipTrigger',
    'Trigger',
    'formatUrlForDisplay',
    'hideLinkTooltip',
    'showLinkTooltip',
    'tooltipMetadata',
  ],
  category: 'pattern',
  owner: '012-F2',
  callers: [
    'src/features/layout/components/content-header/ContentHeader.svelte',
    'src/features/log/components/EntityChip.svelte',
    'src/features/new-workspace/ui/ProviderCard.svelte',
    'src/lib/components/workspace/creation/WorkspaceSetupCard.svelte',
    'src/lib/component-catalog/renderers/NavigationHelpCatalogPreview.svelte',
    'src/lib/components/chat/AgentInputArea.svelte',
    'src/lib/components/chat/AgentSubscriptions.svelte',
    'src/lib/components/chat/ChatHeader.svelte',
    'src/lib/components/chat/ContextEngineToolCall.svelte',
    'src/lib/components/chat/EventWakeupBanner.svelte',
    'src/lib/components/chat/InlineAgentAvatar.svelte',
    'src/lib/components/chat/MessageActions.svelte',
    'src/lib/components/chat/SuggestedPrompts.svelte',
    'src/lib/components/chat/input/ContextPickerButton.svelte',
    'src/lib/components/chat/input/SimpleRichInput.svelte',
    'src/lib/components/file-explorer/VSCodeFileExplorer.svelte',
    'src/lib/components/layout/DaemonStatusIndicator.svelte',
    'src/lib/components/layout/WindowTitleBar.svelte',
    'src/lib/components/layout/panel-system/PanelLayoutHeader.svelte',
    'src/lib/components/layout/panel-system/PanelTabBar.svelte',
    'src/lib/components/layout/sidebar-nav/SidebarPanel.svelte',
    'src/lib/components/layout/sidebar-nav/cards/ChiefCard.svelte',
    'src/lib/components/modals/PullConflictDialog.svelte',
    'src/lib/components/notes/primitives/DiagramBlock.svelte',
    'src/lib/components/settings/AIBehaviorSidebar.svelte',
    'src/lib/components/terminal/QuakeTerminalOverlay.svelte',
    'src/lib/components/terminal/RootQuakeTerminalOverlay.svelte',
    'src/lib/components/tiptap/BubbleMenu.svelte',
    'src/lib/components/tiptap/ContextMentionNodeView.svelte',
    'src/lib/components/tiptap/PasteChipNodeView.svelte',
    'src/lib/components/tiptap/TaskItemNodeView.svelte',
    'src/lib/components/ui/CopyButton.svelte',
    'src/lib/components/ui/NavigationButtons.svelte',
    'src/lib/components/ui/SaveIndicator.svelte',
    'src/lib/components/ui/button/button.svelte',
    'src/lib/components/ui/grouped-combobox/grouped-combobox.svelte',
    'src/lib/components/ui/indicators/AgentBadge.svelte',
    'src/lib/components/ui/list/ListItem.svelte',
    'src/lib/components/ui/searchable-combobox/searchable-combobox.svelte',
    'src/lib/components/ui/sidebar/sidebar-menu-button.svelte',
    'src/lib/components/ui/sidebar/sidebar-provider.svelte',
    'src/lib/components/workspace/TaskProgressBar.svelte',
    'src/lib/components/workspace/WorkspaceCard.svelte',
    'src/lib/components/workspace/initializer/BranchSelector.svelte',
    'src/lib/components/workspace/initializer/IssueSuggestions.svelte',
    'src/lib/components/workspace/initializer/SetupScriptEditor.svelte',
    'src/lib/components/workspace/sidebar/BranchDisplay.svelte',
    'src/lib/components/workspace/sidebar/ContextItemRow.svelte',
    'src/lib/components/workspace/sidebar/FileChangesSection.svelte',
    'src/lib/components/workspace/sidebar/FlameGraph.svelte',
    'src/lib/components/workspace/sidebar/McpServersSection.svelte',
    'src/lib/components/workspace/sidebar/MergePanel.svelte',
    'src/lib/components/workspace/sidebar/WorkspaceProgressCard.svelte',
    'src/lib/components/workspace/sidebar/WorkspaceTokenUsage.svelte',
    'src/routes/(app)/+layout.svelte',
  ],
  replacement: null,
  characterizationTest: 'src/lib/components/ui/tooltip/tooltip.test.ts',
  removalGate: 'Retain while delay, keyboard focus, Escape, portal, and reduced-motion tests pass.',
  dynamicImports: ['src/features/navigation/link-handler.ts'],
  fixtures: tooltipFixtures,
});
