import { parseUiComponentMetadata } from '../component-metadata';
import { textareaFixtures } from './textarea.fixtures';

export const textareaMetadata = parseUiComponentMetadata({
  id: 'textarea',
  source: 'src/lib/components/ui/textarea/textarea.svelte',
  publicImport: '$lib/components/ui/textarea',
  legacyImports: ['$lib/components/ui/textarea/textarea.svelte'],
  exports: ['Textarea', 'textareaMetadata'],
  category: 'primitive',
  owner: '007-B2',
  callers: [
    'src/lib/component-catalog/renderers/ContentFieldCatalogPreview.svelte',
    'src/lib/component-catalog/renderers/FieldPreviewCell.svelte',
    'src/lib/components/chat/MessageEditor.svelte',
    'src/lib/components/chat/QueuedMessageList.svelte',
    'src/lib/components/chat/proposals/ProposalCard.svelte',
    'src/lib/components/modals/ReplaceAgentModal.svelte',
    'src/lib/components/patterns/settings/custom-controls.ts',
    'src/lib/components/tiptap/CommentDialog.svelte',
    'src/lib/components/tiptap/LaunchFromSelectionDialog.svelte',
    'src/lib/components/tiptap/MermaidBlockNodeView.svelte',
    'src/lib/components/ui/ask-user-questions/ask-user-questions.svelte',
    'src/lib/components/ui/message-composer/message-composer.svelte',
    'src/lib/components/workspace/CommentSystemDemo.svelte',
    'src/lib/components/workspace/PullRequestCreator.svelte',
    'src/lib/components/workspace/WorkspaceSidebarHeader.svelte',
    'src/lib/components/workspace/sidebar/CommitDrawer.svelte',
    'src/lib/components/workspace/sidebar/MergePanel.svelte',
    'src/lib/components/workspace/sidebar/PRSection.svelte',
    'src/lib/components/workspace/sidebar/WorkspaceProgressCard.svelte',
  ],
  replacement: null,
  characterizationTest: 'src/lib/components/ui/textarea/textarea.test.ts',
  removalGate: 'Retain while exported and binding, resize, validation, and fixture tests pass.',
  dynamicImports: [],
  fixtures: textareaFixtures,
});
