/**
 * Panel Layout Slice - Public API
 *
 * Re-exports types, actions, selectors, and reducer for the panel layout slice.
 */

// Types
export type {
  PanelTab,
  PanelTabType,
  PanelState,
  PanelLayoutNode,
  WorkspacePanelLayout,
  WorkspacePanelLayoutState,
  PanelLayoutSliceState,
  RecentlyClosedTab,
  LayoutSnapshot,
  FocusHistoryEntry,
  SavedExpandSizes,
} from "./panel-layout-types";

export {
  PANEL_LAYOUT_STORAGE_KEY_PREFIX,
  MAX_RECENTLY_CLOSED,
  MAX_LAYOUT_HISTORY,
  MAX_FOCUS_HISTORY,
  HISTORY_PERSIST_DEBOUNCE_MS,
  EXPANDED_SHARE,
} from "./panel-layout-types";

// Actions
export {
  initializeLayout,
  loadLayoutHistory,
  openTab,
  openTabInAdjacentOrSplit,
  closeTab,
  closeActiveTab,
  closeTabsByType,
  closeTabsByAgentId,
  reopenClosedTab,
  setActiveTab,
  selectNextTab,
  selectPreviousTab,
  reorderTabs,
  moveTabToPanel,
  moveTabToSplit,
  moveTabToSplitLevel,
  closeOtherTabs,
  closeTabsToRight,
  closeAllTabs,
  closeAllOthersEverywhere,
  focusPanel,
  splitPanel,
  closePanel,
  updateSizes,
  updateSplitSizes,
  toggleExpandPanel,
  resetLayout,
  applyPreset,
  createGridLayout,
  goBack,
  goForward,
  goBackInFocusHistory,
  goForwardInFocusHistory,
  setDeferSpecTab,
  consumePendingFocus,
  reconcileStaleAgentTabs,
  clearPanelLayout,
  updateTabTitle,
  updateTabBrowserUrl,
  updateTabFavicon,
  updateFileTabPath,
  panelLayoutReducer,
  generatePanelId,
  generateTabId,
  createDefaultLayout,
  emptyWorkspaceState,
} from "./panel-layout-slice";

// Selectors
export {
  selectPanelLayoutWorkspace,
  selectPanelLayoutRoot,
  selectPanels,
  selectPanel,
  selectFocusedPanelId,
  selectFocusedPanel,
  selectHasMultiplePanels,
  selectActiveTab,
  selectActiveTabInPanel,
  selectAllTabs,
  selectTabById,
  selectIsNoteOpen,
  selectIsFileOpen,
  selectPanelIds,
  selectRecentlyClosed,
  selectHasRecentlyClosed,
  selectLayoutHistory,
  selectHistoryIndex,
  selectHistoryLoaded,
  selectCanGoBack,
  selectCanGoForward,
  selectFocusHistory,
  selectFocusHistoryIndex,
  selectExpandedPanelId,
  selectDeferSpecTab,
  selectPendingFocusTabId,
  getWorkspacePanelLayout,
} from "./panel-layout-selectors";

