import type { UiComponentMetadata } from '../component-metadata';
import { menuFixtures } from './menu.fixtures';

export const menuSemantics = {
  interaction: 'command',
  selectionReplacement: '$lib/components/ui/select',
} as const;

export const menuMetadata = {
  id: 'menu',
  source: 'src/lib/components/ui/menu/index.ts',
  publicImport: '$lib/components/ui/menu',
  legacyImports: ['$lib/components/ui/dropdown-menu.svelte'],
  exports: [
    'CheckboxGroup',
    'CheckboxItem',
    'CommandItem',
    'Content',
    'Item',
    'Menu',
    'MenuItem',
    'MenuSub',
    'Portal',
    'RadioGroup',
    'RadioItem',
    'Root',
    'Separator',
    'StackedContent',
    'StackedMenuGroup',
    'StackedMenuItem',
    'Sub',
    'SubContent',
    'SubTrigger',
    'Trigger',
    'menuMetadata',
    'menuSemantics',
  ],
  category: 'primitive',
  owner: '007-B5',
  callers: [
    'src/features/external-editors/components/OpenComboButton.svelte',
    'src/features/hud/components/HudBackendMenu.svelte',
    'src/features/hud/components/HudHeaderFilters.svelte',
    'src/features/layout/components/ViewSettingsDropdown.svelte',
    'src/features/layout/tab-types/ActivityChangesTabType.svelte',
    'src/features/layout/tab-types/AgentTabType.svelte',
    'src/features/layout/tab-types/AgentViewSettingsDropdown.svelte',
    'src/features/layout/tab-types/DiffTabType.svelte',
    'src/features/layout/tab-types/FileTabType.svelte',
    'src/features/layout/tab-types/NoteTabType.svelte',
    'src/features/layout/tab-types/NoteViewSettingsDropdown.svelte',
    'src/lib/component-catalog/renderers/OverlayCatalogPreview.svelte',
    'src/lib/components/chat/input/SimpleRichInput.svelte',
    'src/lib/components/layout/DaemonStatusIndicator.svelte',
    'src/lib/components/layout/panel-system/PanelTabBar.svelte',
    'src/lib/components/layout/sidebar-nav/SidebarPanel.svelte',
    'src/lib/components/settings/DeviceRow.svelte',
    'src/lib/components/settings/ProviderPathConfig.svelte',
    'src/lib/components/ui/ImageActionsMenu.svelte',
    'src/lib/components/ui/dropdown-menu.svelte',
    'src/lib/components/ui/sidebar-context-menu/SidebarDropdownMenuItems.svelte',
  ],
  replacement: null,
  characterizationTest: 'src/lib/components/ui/menu/menu.test.ts',
  removalGate:
    'Retain while exported; command, checkbox-item, keyboard, and focus tests must pass.', // i18n-ignore (design-system catalog metadata)
  dynamicImports: [],
  fixtures: menuFixtures,
} satisfies UiComponentMetadata;
