import { parseUiComponentMetadata } from '../component-metadata';
import { toastFixtures } from './toast.fixtures';

export const toastMetadata = parseUiComponentMetadata({
  id: 'toast',
  source: 'src/lib/components/ui/toast/index.ts',
  publicImport: '$lib/components/ui/toast',
  legacyImports: ['$lib/components/ui/toast/Toast.svelte'],
  exports: [
    'AgentAttentionToast',
    'AgentAttentionToastComponent',
    'AgentFailureToast',
    'AgentFailureToastComponent',
    'ErrorToast',
    'ErrorToastComponent',
    'ExternalToast',
    'TOAST_COUNTDOWN_CLASS',
    'TOAST_COUNTDOWN_NO_HOVER_PAUSE_CLASS',
    'Toast',
    'ToastCloseButton',
    'ToastComponent',
    'UpdateToast',
    'UpdateToastComponent',
    'loadAgentAttentionToast',
    'loadAgentFailureToast',
    'loadErrorToast',
    'loadToast',
    'loadUpdateToast',
    'toast',
    'toastMetadata',
    'withToastCountdown',
  ],
  category: 'pattern',
  owner: '007-B1',
  callers: [
    'src/lib/component-catalog/renderers/ToastCatalogPreview.svelte',
    'src/lib/components/layout/DaemonStatusIndicator.svelte',
    'src/lib/components/patterns/notify/index.ts',
    'src/lib/components/patterns/notify/notify.ts',
    'src/routes/(app)/+layout.svelte',
  ],
  replacement: null,
  characterizationTest: 'src/lib/components/ui/toast/Toast.test.ts',
  removalGate: 'Retain while toast styling, countdown, actions, and catalog coverage pass.',
  dynamicImports: ['src/features/agent/agent-attention-toast-service.ts'],
  fixtures: toastFixtures,
});
