<script lang="ts">
  /**
   * CopyErrorButton - Vercel-inspired minimal copy button
   *
   * Clean, text-based button that copies error details formatted for support.
   */
  import { onDestroy } from 'svelte';
  import { fade } from 'svelte/transition';
  import { cubicInOut } from 'svelte/easing';
  import Fa from 'svelte-fa';
  import { faCheck } from '@fortawesome/free-solid-svg-icons';
  import type { AppError } from '$lib/utils/error-handler.svelte';
  import { errorReporter } from '$lib/utils/error-reporter';
  import { workspaceStore } from '$features/workspace/workspace.store.svelte';
  import { toast } from '$lib/components/ui/toast';

  interface Props {
    error: AppError;
    /** Show label text or just icon */
    showLabel?: boolean;
    /** Custom label text */
    label?: string;
    /** Callback when copied */
    onCopied?: () => void;
    /** Additional class names */
    class?: string;
  }

  let {
    error,
    showLabel = true,
    label = 'Copy',
    onCopied,
    class: className = '',
  }: Props = $props();

  let isCopied = $state(false);
  let copyTimeout: ReturnType<typeof setTimeout> | null = null;

  /**
   * Format the error for support in a clean, readable format
   * Includes all diagnostic info needed for debugging
   */
  function formatForSupport(): string {
    const report = errorReporter.generateReport(error, {
      workspaceId: workspaceStore.current?.id,
    });

    // Create a compact but comprehensive format
    const lines = [
      '## 🐛 Error Report',
      '',
      `**Error:** ${error.title}`,
      `**Message:** ${error.message}`,
      '',
      '---',
      '',
      '### Diagnostic Info',
      '```yaml',
      `error_id: ${error.id}`,
      `type: ${error.type}`,
      `timestamp: ${error.timestamp.toISOString()}`,
      `recoverable: ${error.recoverable}`,
      '```',
      '',
    ];

    // Add context if available (filtered for relevant info)
    if (error.context) {
      const relevantContext = filterSensitiveInfo(error.context);
      if (Object.keys(relevantContext).length > 0) {
        lines.push('### Context');
        lines.push('```json');
        lines.push(JSON.stringify(relevantContext, null, 2));
        lines.push('```');
        lines.push('');
      }
    }

    // Add stack trace (trimmed to relevant parts)
    if (error.stack) {
      const trimmedStack = trimStackTrace(error.stack);
      lines.push('### Stack Trace');
      lines.push('```');
      lines.push(trimmedStack);
      lines.push('```');
    }

    lines.push('');
    lines.push('---');
    lines.push('*Generated by Intent • ' + new Date().toLocaleDateString() + '*');

    return lines.join('\n');
  }

  /**
   * Filter out sensitive information from context
   */
  function filterSensitiveInfo(context: Record<string, any>): Record<string, any> {
    const sensitiveKeys = ['password', 'token', 'secret', 'key', 'auth', 'cookie', 'session'];
    const filtered: Record<string, any> = {};

    for (const [key, value] of Object.entries(context)) {
      const lowerKey = key.toLowerCase();
      if (sensitiveKeys.some((s) => lowerKey.includes(s))) {
        filtered[key] = '[REDACTED]';
      } else if (typeof value === 'object' && value !== null) {
        filtered[key] = filterSensitiveInfo(value);
      } else {
        filtered[key] = value;
      }
    }

    return filtered;
  }

  /**
   * Trim stack trace to most relevant parts
   */
  function trimStackTrace(stack: string): string {
    const lines = stack.split('\n');
    // Keep first 15 lines max, prioritizing non-node_modules lines
    const relevantLines = lines.filter((line) => !line.includes('node_modules')).slice(0, 10);
    const nodeModulesLines = lines.filter((line) => line.includes('node_modules')).slice(0, 5);

    if (nodeModulesLines.length > 0) {
      return [...relevantLines, '  ... (dependency frames)', ...nodeModulesLines.slice(0, 3)].join(
        '\n',
      );
    }
    return relevantLines.join('\n');
  }

  async function handleCopy() {
    try {
      const formatted = formatForSupport();
      await navigator.clipboard.writeText(formatted);

      isCopied = true;
      toast.success('Error details copied! Paste into a support message or issue.');

      if (copyTimeout) clearTimeout(copyTimeout);
      copyTimeout = setTimeout(() => {
        isCopied = false;
      }, 3000);

      onCopied?.();
    } catch (err) {
      toast.error('Failed to copy to clipboard');
    }
  }

  onDestroy(() => {
    if (copyTimeout) clearTimeout(copyTimeout);
  });
</script>

<!-- Vercel-style minimal copy button -->
<button
  onclick={handleCopy}
  class="text-[11px] font-medium transition-all duration-200 flex items-center gap-1.5 {className}
    {isCopied ? 'text-emerald-400' : 'text-neutral-400 hover:text-neutral-100'}"
>
  {#if isCopied}
    <span in:fade={{ duration: 150, easing: cubicInOut }}>
      <Fa icon={faCheck} size="xs" />
    </span>
    {#if showLabel}
      <span>Copied</span>
    {/if}
  {:else}
    {#if showLabel}
      <span>{label}</span>
    {/if}
  {/if}
</button>
