/**
 * TasksBlock TipTap Node Extension
 *
 * This extension allows TipTap to recognize and preserve tasks-block HTML
 * that is generated by the markdown processor for ```tasks code blocks.
 *
 * The tasks-block is rendered as a read-only container that displays
 * proposed tasks with their titles and content.
 *
 * Structure:
 * <div data-type="tasks-block">
 *   <div class="tasks-block-header">...</div>
 *   <div data-type="tasks-block-item">
 *     <div data-type="tasks-block-title">...</div>
 *     <div data-type="tasks-block-content">...</div>
 *   </div>
 *   ...
 * </div>
 */

import { Node } from '@tiptap/core';

/**
 * TasksBlock - Container for proposed tasks
 *
 * This is an atomic node that preserves its HTML content as-is.
 * It's read-only and displays the proposed tasks before they are converted
 * to actual Task Notes.
 *
 * We use addNodeView to render the raw HTML content directly, bypassing
 * TipTap's normal content parsing which would strip unknown elements.
 */
export const TasksBlock = Node.create({
  name: 'tasksBlock',

  group: 'block',

  // Atomic means TipTap treats this as a single unit and doesn't try to parse its content
  atom: true,

  // Store the raw HTML content as an attribute
  addAttributes() {
    return {
      htmlContent: {
        default: '',
        parseHTML: (element) => element.innerHTML,
        renderHTML: () => ({}), // Don't render as attribute
      },
    };
  },

  parseHTML() {
    return [
      {
        tag: 'div[data-type="tasks-block"]',
        getAttrs: (element) => {
          if (typeof element === 'string') return false;
          return {
            htmlContent: element.innerHTML,
          };
        },
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    // Return a simple placeholder - the actual content is rendered by addNodeView
    return [
      'div',
      {
        ...HTMLAttributes,
        'data-type': 'tasks-block',
        class: 'tasks-block',
      },
    ];
  },

  // Use a custom NodeView to render the raw HTML content
  addNodeView() {
    return ({ node }) => {
      const dom = document.createElement('div');
      dom.setAttribute('data-type', 'tasks-block');
      dom.className = 'tasks-block';
      dom.innerHTML = node.attrs.htmlContent || '';

      return {
        dom,
        // Don't allow content editing
        contentDOM: null,
        // Update when attributes change
        update: (updatedNode) => {
          if (updatedNode.type.name !== 'tasksBlock') {
            return false;
          }
          dom.innerHTML = updatedNode.attrs.htmlContent || '';
          return true;
        },
      };
    };
  },
});
