import { parseUiComponentMetadata } from '../component-metadata';
import { labelFixtures } from './label.fixtures';

export const labelMetadata = parseUiComponentMetadata({
  id: 'label',
  source: 'src/lib/components/ui/label/label.svelte',
  publicImport: '$lib/components/ui/label',
  legacyImports: [],
  exports: ['Label', 'labelMetadata'],
  category: 'primitive',
  owner: '007-B2',
  callers: [
    'src/features/collaboration-auth/renderer/CollaborationSignInModal.svelte',
    'src/lib/component-catalog/renderers/ContentFieldCatalogPreview.svelte',
    'src/lib/component-catalog/renderers/FieldPreviewCell.svelte',
    'src/lib/component-catalog/renderers/ModalCatalogPreview.svelte',
    'src/lib/components/GitLabConnectForm.svelte',
    'src/lib/components/debug/DebugPanel.svelte',
    'src/lib/components/modals/InputDialog.svelte',
    'src/lib/components/modals/ShareWorkspaceDialog.svelte',
    'src/lib/components/modals/modal-polish.preview.svelte',
    'src/lib/components/patterns/confirm/ConfirmRequestView.svelte',
    'src/lib/components/patterns/form/FormField.svelte',
    'src/lib/components/patterns/settings/SettingsFieldRow.svelte',
    'src/lib/components/patterns/settings/custom-controls.ts',
    'src/lib/components/workspace/initializer/AddRemoteSetupModal.svelte',
    'src/lib/components/workspace/initializer/SetupScriptTrigger.svelte',
    'src/lib/components/workspace/sidebar/context-picker/BrowserUrlPicker.svelte',
  ],
  replacement: null,
  characterizationTest: 'src/lib/components/ui/label/label.test.ts',
  removalGate: 'Retain while exported and association and fixture tests pass.',
  dynamicImports: [],
  fixtures: labelFixtures,
});
