// Policy tests, not evidence of TCC dialog display or permission attribution.
var prompts = PermissionPrompts()
precondition(prompts.next(accessibility: false, screenRecording: false) == .accessibility)
precondition(prompts.next(accessibility: false, screenRecording: false) == nil)
precondition(prompts.next(accessibility: true, screenRecording: false) == .screenRecording)
precondition(prompts.next(accessibility: true, screenRecording: false) == nil)
precondition(prompts.next(accessibility: true, screenRecording: true) == nil)
precondition(prompts.next(accessibility: false, screenRecording: true) == nil)
var screenOnly = PermissionPrompts()
precondition(screenOnly.next(accessibility: true, screenRecording: false) == .screenRecording)
var trusted = PermissionPrompts()
precondition(trusted.next(accessibility: true, screenRecording: true) == nil)
print("PASS: sequential, explicit-gesture permission prompt policy; denial never loops")
var readiness = PermissionReadiness()
precondition(readiness.observe(requestId: "first", granted: false, now: 0) == nil)
let first = readiness.observe(requestId: "first", granted: true, now: 0)!
for tick in 1...20 {
    precondition(readiness.observe(requestId: "first", granted: true, now: UInt64(tick * 1000)) == nil)
    precondition(!readiness.expire(now: UInt64(tick * 1000)))
    precondition(readiness.state == "pending")
}
readiness.complete(first, ready: true)
precondition(readiness.state == "ready")
let second = readiness.observe(requestId: "second", granted: true, now: 21000)!
readiness.complete(first, ready: true)
precondition(readiness.state == "pending")
precondition(readiness.expire(now: 24000))
readiness.complete(second, ready: true)
precondition(readiness.state == "unavailable")
precondition(readiness.observe(requestId: "second", granted: true, now: 25000) == nil)
let third = readiness.observe(requestId: "third", granted: true, now: 26000)!
precondition(readiness.observe(requestId: "third", granted: false, now: 27000) == nil)
readiness.complete(third, ready: true)
precondition(readiness.state == "unavailable")
print("PASS: delayed SCK readiness, polling cancellation, late completion and successor fencing")
var concurrent = PermissionReadiness()
let owner = concurrent.observe(requestId: "owner", granted: true, now: 0)!
precondition(concurrent.observe(requestId: "other", granted: true, now: 1000) == nil, "A competing request must not replace the pending probe")
precondition(concurrent.generation == owner)
precondition(concurrent.observe(requestId: "owner", granted: true, now: 2000) == nil)
concurrent.complete(owner, ready: true)
let other = concurrent.observe(requestId: "other", granted: true, now: 2001)!
precondition(concurrent.observe(requestId: "owner", granted: true, now: 2002) == nil, "A completed owner must not cancel its successor probe")
precondition(concurrent.generation == other)
concurrent.complete(other, ready: false)
precondition(concurrent.observe(requestId: "other", granted: true, now: 2500) == nil, "Failed observation must not silently retry")
print("PASS: concurrent permission observations retain each request outcome without probe churn")
