import { parseUiComponentMetadata } from '../component-metadata';
import { dialogFixtures } from './dialog.fixtures';

export const dialogMetadata = parseUiComponentMetadata({
  id: 'dialog',
  source: 'src/lib/components/ui/dialog/index.ts',
  publicImport: '$lib/components/ui/dialog',
  legacyImports: [],
  exports: [
    'Close',
    'Content',
    'Description',
    'Dialog',
    'DialogClose',
    'DialogContent',
    'DialogDescription',
    'DialogFooter',
    'DialogHeader',
    'DialogOverlay',
    'DialogPortal',
    'DialogTitle',
    'DialogTrigger',
    'Footer',
    'Header',
    'Overlay',
    'Portal',
    'Root',
    'Title',
    'Trigger',
  ],
  category: 'primitive',
  owner: '007-B4',
  callers: [],
  replacement: null,
  characterizationTest: 'src/lib/components/ui/dialog/dialog.test.ts',
  removalGate: 'Retain while exported; require metadata, fixtures, and behavioral coverage.',
  dynamicImports: [],
  fixtures: dialogFixtures,
});
