export const chatPolishCoverageManifest = Object.freeze({
  conversation: ['single', 'coherent', 'daemon-free', 'read-only'],
  userMessages: ['short', 'long', 'queued', 'optimistic', 'sticky', 'delivered'],
  assistantContent: [
    'prose',
    'rich-markdown',
    'list',
    'link',
    'inline-code',
    'code-block',
    'truncation',
    'suggested-prompts',
    'streaming-text',
    'final-text',
  ],
  thinking: ['before-content', 'between-content', 'after-content'],
  operationalClusters: ['consecutive', 'interrupted', 'grouped', 'ungrouped'],
  tools: [
    'context',
    'search',
    'view',
    'pending',
    'running',
    'successful',
    'failed',
    'cancelled',
    'input-only',
    'output-only',
    'input-and-output',
    'empty',
    'error',
    'long-payload',
    'hidden-result',
    'expanded-detail',
  ],
  responseGroups: ['repeated', 'mixed', 'collapsed', 'expanded'],
  coordination: ['coordinator-message', 'agent-message', 'agent-sent', 'agent-finished'],
  subscriptions: ['after_all-collapsed', 'after_all-expanded', 'immediate-expanded'],
  participants: ['avatar-overflow'],
  wakes: [
    'agent-completion',
    'hook-wake',
    'queued-delivery',
    'retired-hook',
    'active-hook',
    'newly-unblocked-tasks',
  ],
  lifecycle: [
    'changed-files',
    'turn-failure',
    'interruption',
    'retry',
    'recovery',
    'successful-completion',
  ],
  constraints: ['narrow-content', 'long-label', 'accessible-full-text'],
} as const);

export const chatPolishCoverage = Object.freeze(Object.values(chatPolishCoverageManifest).flat());
