/**
 * Attribution Engine
 *
 * Determines the source of changes using a multi-layer strategy:
 * 1. Current provenance context (most accurate)
 * 2. Content-based matching (compare against recorded agent writes)
 * 3. Default to user (last resort)
 *
 * Agent writes are persisted to disk per-workspace for durability across app restarts.
 */

import crypto from 'crypto';
import type { WorkspaceEvent, WorkspaceEventType } from '../../../../features/events/types';
import type { ProvenanceInfo, Actor } from '../../../../shared/types';
import {
  ProvenanceContextManager,
  getProvenanceContextManager,
} from './provenance-context-manager';
import { Logger } from '../../../../shared/logger';
import { v4 as uuidv4 } from 'uuid';
import { FileTrackingStorage } from '../../../file-tracking/main/file-tracking-storage';
import type { AgentAttribution } from '../../../file-tracking/types';

const logger = new Logger('AttributionEngine');

export interface ChangeDetails {
  filePath?: string;
  action: 'create' | 'modify' | 'delete' | 'rename';
  additions?: number;
  deletions?: number;
  diff?: string;
  oldContent?: string;
  newContent?: string;
  source?: 'git' | 'filesystem' | 'editor' | 'auto-save' | 'sync';
  trigger?: string; // What triggered this change (e.g., "git-pull", "auto-format", etc.)
}

/**
 * Represents an agent's file write with content hash for matching
 */
interface AgentWrite {
  agentId: string;
  agentName: string;
  sessionId?: string;
  turnNumber?: number;
  messageId?: string;
  contentHash: string; // Hash of content written by agent
  timestamp: number; // When write happened
  workspaceId?: string; // Workspace this write belongs to
}

/**
 * Hash function for content comparison using crypto
 * Uses SHA-256 for robust collision resistance
 */
function hashContent(content: string): string {
  return crypto.createHash('sha256').update(content, 'utf8').digest('hex').substring(0, 16);
}

/**
 * Attribution engine for determining change source
 *
 * Uses content-based matching for precise attribution:
 * - Tracks what content each agent wrote to each file
 * - Matches by content hash when file change is detected
 * - 100% accurate - no timing-based false positives
 */
export class AttributionEngine {
  private static instance: AttributionEngine;
  private contextManager: ProvenanceContextManager;
  private debug: boolean = false;

  // Content-based tracking: Map of filePath -> AgentWrite
  private agentWrites: Map<string, AgentWrite> = new Map();

  // Cleanup timer
  private cleanupTimer: NodeJS.Timeout | null = null;

  // System file patterns that indicate system-initiated changes
  private systemFilePatterns = [
    /^\.git\//,
    /^\.workspace\//,
    /node_modules\//,
    /\.lock$/,
    /package-lock\.json$/,
    /yarn\.lock$/,
    /pnpm-lock\.yaml$/,
    /\.DS_Store$/,
    /Thumbs\.db$/,
    /\.vscode\/settings\.json$/,
    /\.idea\//,
  ];

  // Patterns that indicate auto-generated or formatted files
  private autoGeneratedPatterns = [
    /\.min\.(js|css)$/,
    /\.map$/,
    /dist\//,
    /build\//,
    /coverage\//,
    /\.next\//,
    /\.svelte-kit\//,
  ];

  // Track which workspaces have been loaded from disk
  private loadedWorkspaces: Set<string> = new Set();

  // Pending save operations per workspace (debounced)
  private pendingSaves: Map<string, NodeJS.Timeout> = new Map();

  // TTL for agent writes (24 hours) - after this, old writes are cleaned up
  private readonly AGENT_WRITE_TTL_MS = 24 * 60 * 60 * 1000;

  // Cache for attribution results to avoid redundant work on repeated polls
  // Map of "workspaceId:filePath:contentHash" -> { result: AgentWrite | null, timestamp: number }
  private attributionCache: Map<string, { result: AgentWrite | null; timestamp: number }> =
    new Map();
  // Cache TTL (5 minutes) - attributions are stable unless agent writes change
  private readonly ATTRIBUTION_CACHE_TTL_MS = 5 * 60 * 1000;

  constructor(options?: { debug?: boolean; agentContextTTL?: number }) {
    this.debug = options?.debug ?? false;
    this.contextManager = getProvenanceContextManager({ debug: options?.debug });
    // Start periodic cleanup of old agent writes
    this.startPeriodicCleanup();
  }

  /**
   * Start periodic cleanup of old agent writes (runs every hour)
   */
  private startPeriodicCleanup(): void {
    // Clean up old writes every hour
    this.cleanupTimer = setInterval(
      () => {
        this.cleanupOldWrites();
        this.cleanupAttributionCache();
      },
      60 * 60 * 1000,
    );
  }

  /**
   * Clean up agent writes older than TTL
   */
  private cleanupOldWrites(): void {
    const now = Date.now();
    let cleanedCount = 0;
    const workspacesToSave = new Set<string>();

    for (const [filePath, write] of this.agentWrites.entries()) {
      if (now - write.timestamp > this.AGENT_WRITE_TTL_MS) {
        this.agentWrites.delete(filePath);
        cleanedCount++;
        // Use explicit null/undefined check to allow empty string workspaceId
        if (write.workspaceId !== undefined && write.workspaceId !== null) {
          workspacesToSave.add(write.workspaceId);
        }
      }
    }

    if (cleanedCount > 0) {
      logger.info('[AttributionEngine] Cleaned up old agent writes', {
        count: cleanedCount,
        remaining: this.agentWrites.size,
      });

      // Persist the cleanup for each affected workspace
      for (const workspaceId of workspacesToSave) {
        this.persistAgentWrites(workspaceId);
      }
    }
  }

  /**
   * Invalidate attribution cache entries for a specific file path.
   * Called when a new agent write is recorded to ensure the next poll
   * re-evaluates attribution.
   */
  private invalidateAttributionCache(filePath: string, workspaceId?: string): void {
    // Remove all cache entries for this file path (across all content hashes)
    const prefix = `${workspaceId || ''}:${filePath}:`;
    for (const key of this.attributionCache.keys()) {
      if (key.startsWith(prefix)) {
        this.attributionCache.delete(key);
      }
    }
  }

  /**
   * Clean up expired attribution cache entries.
   * Called periodically to prevent memory growth.
   */
  private cleanupAttributionCache(): void {
    const now = Date.now();
    for (const [key, entry] of this.attributionCache.entries()) {
      if (now - entry.timestamp > this.ATTRIBUTION_CACHE_TTL_MS) {
        this.attributionCache.delete(key);
      }
    }
  }

  /**
   * Ensure agent writes are loaded for a workspace.
   * This is a public method that should be called during workspace initialization
   * and before any attribution operations.
   */
  async ensureWorkspaceLoaded(workspaceId: string): Promise<void> {
    await this.loadAgentWritesForWorkspace(workspaceId);
  }

  /**
   * Load agent writes from disk for a workspace (lazy loading)
   */
  private async loadAgentWritesForWorkspace(workspaceId: string): Promise<void> {
    if (this.loadedWorkspaces.has(workspaceId)) {
      return;
    }

    try {
      const storage = FileTrackingStorage.getInstance(workspaceId);
      const attributions = await storage.loadAttributions();

      // Merge loaded attributions into in-memory map
      for (const [filePath, attr] of attributions.entries()) {
        // Convert AgentAttribution to AgentWrite format
        const write: AgentWrite = {
          agentId: attr.agentId,
          agentName: attr.agentName,
          sessionId: attr.sessionId,
          turnNumber: attr.turnNumber,
          messageId: attr.messageId,
          contentHash: (attr as any).contentHash || '',
          timestamp: attr.timestamp,
          workspaceId,
        };
        this.agentWrites.set(filePath, write);
      }

      this.loadedWorkspaces.add(workspaceId);
      logger.info('[AttributionEngine] Loaded agent writes from disk', {
        workspaceId,
        count: attributions.size,
      });
    } catch (error) {
      logger.error('[AttributionEngine] Failed to load agent writes from disk', {
        workspaceId,
        error,
      });
    }
  }

  /**
   * Persist agent writes to disk for a workspace (debounced)
   */
  private persistAgentWrites(workspaceId: string): void {
    // Clear any pending save for this workspace
    const pending = this.pendingSaves.get(workspaceId);
    if (pending) {
      clearTimeout(pending);
    }

    // Debounce saves to avoid too many disk writes
    const timeout = setTimeout(async () => {
      this.pendingSaves.delete(workspaceId);
      await this.doSaveAgentWrites(workspaceId);
    }, 500);

    this.pendingSaves.set(workspaceId, timeout);
  }

  /**
   * Actually save agent writes to disk
   */
  private async doSaveAgentWrites(workspaceId: string): Promise<void> {
    try {
      const storage = FileTrackingStorage.getInstance(workspaceId);

      // Filter writes for this workspace and convert to AgentAttribution format
      const attributions = new Map<string, AgentAttribution>();
      logger.info('[AttributionEngine] doSaveAgentWrites - filtering writes', {
        workspaceId,
        totalWrites: this.agentWrites.size,
      });

      for (const [filePath, write] of this.agentWrites.entries()) {
        logger.debug('[AttributionEngine] Checking write for filtering', {
          filePath,
          writeWorkspaceId: write.workspaceId,
          targetWorkspaceId: workspaceId,
          matches: write.workspaceId === workspaceId,
        });

        if (write.workspaceId === workspaceId) {
          attributions.set(filePath, {
            agentId: write.agentId,
            agentName: write.agentName,
            sessionId: write.sessionId || '',
            turnNumber: write.turnNumber || 0,
            messageId: write.messageId,
            toolCallId: undefined,
            timestamp: write.timestamp,
            // Store contentHash in the attribution for matching
            ...(write.contentHash && { contentHash: write.contentHash }),
          } as AgentAttribution);
        }
      }

      logger.info('[AttributionEngine] About to save attributions', {
        workspaceId,
        count: attributions.size,
      });

      await storage.saveAttributions(attributions);
      logger.debug('[AttributionEngine] Persisted agent writes to disk', {
        workspaceId,
        count: attributions.size,
      });
    } catch (error) {
      logger.error('[AttributionEngine] Failed to persist agent writes to disk', {
        workspaceId,
        error,
      });
    }
  }

  /**
   * Record an agent's file write for content-based attribution.
   * Call this after an agent successfully writes a file.
   * Agent writes are persisted to disk for durability across app restarts.
   *
   * @param agentInfo - Information about the agent
   * @param filePath - The file path that was written (can be absolute or relative)
   * @param content - The content that was written
   * @param workspacePath - Optional workspace path to extract relative path from absolute paths
   * @param workspaceId - Optional workspace ID for persistence
   */
  recordAgentWrite(
    agentInfo: {
      agentId: string;
      agentName: string;
      sessionId?: string;
      turnNumber?: number;
      messageId?: string;
    },
    filePath: string,
    content: string,
    workspacePath?: string,
    workspaceId?: string,
  ): void {
    // Extract relative path if workspacePath is provided and filePath is absolute
    const relativePath = this.extractRelativePath(filePath, workspacePath);
    const normalizedPath = this.normalizePath(relativePath);
    const contentHash = hashContent(content);

    this.agentWrites.set(normalizedPath, {
      agentId: agentInfo.agentId,
      agentName: agentInfo.agentName,
      sessionId: agentInfo.sessionId,
      turnNumber: agentInfo.turnNumber,
      messageId: agentInfo.messageId,
      contentHash,
      timestamp: Date.now(),
      workspaceId,
    });

    // Invalidate attribution cache for this file path
    // This ensures the next poll will re-evaluate attribution with the new agent write
    this.invalidateAttributionCache(normalizedPath, workspaceId);

    // Always log agent writes - this is critical for debugging attribution issues
    logger.info('[AttributionEngine] Recorded agent write', {
      originalPath: filePath,
      normalizedPath,
      workspacePath,
      workspaceId,
      agentId: agentInfo.agentId,
      agentName: agentInfo.agentName,
      contentHash,
      contentLength: content.length,
      pendingWrites: this.agentWrites.size,
    });

    // Persist to disk if workspaceId is provided (not undefined or null)
    // Note: Empty string is a valid workspaceId, so we check for undefined/null explicitly
    if (workspaceId !== undefined && workspaceId !== null) {
      this.persistAgentWrites(workspaceId);
    } else {
      logger.warn('[AttributionEngine] Agent write not persisted - workspaceId is missing', {
        originalPath: filePath,
        normalizedPath,
        workspaceId,
        agentId: agentInfo.agentId,
      });
    }
  }

  /**
   * Extract relative path from an absolute path given a workspace path.
   * If the filePath starts with workspacePath, returns the relative portion.
   * Otherwise returns the original filePath.
   */
  private extractRelativePath(filePath: string, workspacePath?: string): string {
    if (!workspacePath || !filePath) return filePath;

    // Normalize both paths for comparison
    const normalizedFilePath = filePath.replace(/\\/g, '/');
    const normalizedWorkspacePath = workspacePath.replace(/\\/g, '/').replace(/\/+$/, '');

    // Check if filePath starts with workspacePath
    if (normalizedFilePath.startsWith(`${normalizedWorkspacePath}/`)) {
      return normalizedFilePath.substring(normalizedWorkspacePath.length + 1);
    }

    // Also check without leading slash (in case workspacePath has trailing slash issues)
    if (normalizedFilePath.startsWith(normalizedWorkspacePath)) {
      const remainder = normalizedFilePath.substring(normalizedWorkspacePath.length);
      if (remainder.startsWith('/')) {
        return remainder.substring(1);
      }
    }

    return filePath;
  }

  /**
   * Normalize a file path for consistent lookups.
   * Handles various path formats from different sources (git, filesystem, tools).
   */
  private normalizePath(filePath: string): string {
    if (!filePath) return '';

    const normalized = filePath
      // Convert Windows backslashes to forward slashes
      .replace(/\\/g, '/')
      // Remove leading slashes
      .replace(/^\/+/, '')
      // Remove trailing slashes
      .replace(/\/+$/, '')
      // Collapse multiple slashes
      .replace(/\/+/g, '/')
      // Remove ./ prefix
      .replace(/^\.\//, '');

    return normalized;
  }

  /**
   * Load agent writes for a workspace from disk (async version for external use)
   */
  async loadAgentWrites(workspaceId: string): Promise<void> {
    await this.loadAgentWritesForWorkspace(workspaceId);
  }

  /**
   * Check if file content matches a recorded agent write.
   *
   * We only attribute to an agent when the content hash matches exactly.
   * This avoids false-positive agent attribution when a user modifies a file
   * shortly after an agent write.
   *
   * NOTE: We do NOT delete the write after matching to support multiple edits
   * to the same file. Old writes are cleaned up via TTL-based cleanup.
   */
  private async matchAgentWrite(
    filePath: string,
    content: string,
    workspaceId?: string,
  ): Promise<AgentWrite | null> {
    // Ensure workspace is loaded before trying to match
    if (workspaceId) {
      await this.ensureWorkspaceLoaded(workspaceId);
    }

    const normalizedPath = this.normalizePath(filePath);

    // Compute content hash early - used for both caching and matching
    const contentHash = hashContent(content);

    // Check cache first to avoid redundant work on repeated polls
    const cacheKey = `${workspaceId || ''}:${normalizedPath}:${contentHash}`;
    const cached = this.attributionCache.get(cacheKey);
    const now = Date.now();
    if (cached && now - cached.timestamp < this.ATTRIBUTION_CACHE_TTL_MS) {
      // Cache hit - return cached result without logging
      return cached.result;
    }

    const write = this.agentWrites.get(normalizedPath);

    if (!write) {
      // No agent write for this path - cache the null result
      this.attributionCache.set(cacheKey, { result: null, timestamp: now });
      return null;
    }

    // Check if content hash matches
    if (contentHash === write.contentHash) {
      // Content matches - this was an agent write
      // NOTE: We do NOT delete the write to support multiple edits to the same file
      // Old writes are cleaned up via TTL-based cleanup (24 hours)
      // Use debug level to avoid spamming logs on every poll
      logger.debug('[AttributionEngine] Content matched agent write', {
        filePath: normalizedPath,
        agentId: write.agentId,
        agentName: write.agentName,
        contentHash,
      });

      // Cache the positive result
      this.attributionCache.set(cacheKey, { result: write, timestamp: now });
      return write;
    }

    // Content doesn't match - cache the negative result
    this.attributionCache.set(cacheKey, { result: null, timestamp: now });

    // Log mismatch for debugging (only when there was a potential match)
    const timeSinceWrite = now - write.timestamp;
    logger.debug('[AttributionEngine] Content hash mismatch for agent write', {
      filePath: normalizedPath,
      agentId: write.agentId,
      expectedHash: write.contentHash,
      actualHash: contentHash,
      contentLength: content.length,
      timeSinceWriteMs: timeSinceWrite,
    });
    return null;
  }

  /**
   * Get singleton instance
   */
  static getInstance(options?: { debug?: boolean; agentContextTTL?: number }): AttributionEngine {
    if (!AttributionEngine.instance) {
      AttributionEngine.instance = new AttributionEngine(options);
    }
    return AttributionEngine.instance;
  }

  /**
   * Check if a file path indicates a system-initiated change
   */
  private isSystemFile(filePath?: string): boolean {
    if (!filePath) return false;

    return (
      this.systemFilePatterns.some((pattern) => pattern.test(filePath)) ||
      this.autoGeneratedPatterns.some((pattern) => pattern.test(filePath))
    );
  }

  /**
   * Determine if a change is likely system-initiated based on heuristics
   */
  private isSystemInitiated(changeDetails: ChangeDetails): boolean {
    // Check if explicitly marked as system source
    if (changeDetails.source === 'git' || changeDetails.source === 'sync') {
      return true;
    }

    // Check if it's a system file
    if (this.isSystemFile(changeDetails.filePath)) {
      return true;
    }

    // Check for auto-save patterns
    if (changeDetails.source === 'auto-save') {
      return true;
    }

    // Check for specific triggers that indicate system operations
    const systemTriggers = ['git-pull', 'git-merge', 'auto-format', 'prettier', 'eslint-fix'];
    if (changeDetails.trigger && systemTriggers.includes(changeDetails.trigger)) {
      return true;
    }

    return false;
  }

  /**
   * Attribute a change to its source using multi-layer strategy
   *
   * Strategy (in order of precedence):
   * 1. System changes (git, node_modules, lock files, etc.)
   * 2. Active provenance context (agent tool is actively executing)
   * 3. Content-based matching (compare content against recorded agent writes)
   * 4. Default to user
   *
   * @param changeDetails - Details about the change
   * @param workspaceId - Optional workspace ID for loading agent writes
   */
  async attributeChange(
    changeDetails: ChangeDetails,
    workspaceId?: string,
  ): Promise<ProvenanceInfo> {
    const filePath = changeDetails.filePath || 'unknown';

    // Layer 0: Check if this is a system-initiated change
    if (this.isSystemInitiated(changeDetails)) {
      logger.debug(`[AttributionEngine] System-initiated change: ${filePath}`, {
        source: changeDetails.source,
        trigger: changeDetails.trigger,
      });

      return {
        source: 'system',
        execution: {
          reasoning: `System change detected: ${changeDetails.trigger || changeDetails.source || 'automatic'}`,
        },
      };
    }

    // Layer 1: Check current provenance context (most accurate - agent tool is actively executing)
    const currentContext = this.contextManager.getCurrentContext();
    if (currentContext) {
      logger.info(`[AttributionEngine] Using provenance context for ${filePath}`, {
        source: currentContext.source,
        agentId: currentContext.agent?.id,
        agentName: currentContext.agent?.name,
      });

      return {
        source: currentContext.source,
        agent: currentContext.agent,
        chat: currentContext.chat,
        execution: currentContext.execution,
      };
    }

    // Layer 2: Content-based matching (compare against recorded agent writes)
    if (changeDetails.filePath && changeDetails.newContent) {
      const agentWrite = await this.matchAgentWrite(
        changeDetails.filePath,
        changeDetails.newContent,
        workspaceId,
      );
      if (agentWrite) {
        // Logging is done in matchAgentWrite
        return {
          source: 'agent',
          agent: {
            id: agentWrite.agentId,
            name: agentWrite.agentName,
            sessionId: agentWrite.sessionId,
          },
          chat:
            agentWrite.turnNumber || agentWrite.messageId
              ? {
                turnNumber: agentWrite.turnNumber,
                messageId: agentWrite.messageId,
              }
              : undefined,
        };
      }
    }

    // Layer 3: Default to user (no context or content match found)
    logger.debug(`[AttributionEngine] Defaulting to user for ${filePath}`, {
      hasContent: !!changeDetails.newContent,
      contentLength: changeDetails.newContent?.length || 0,
      pendingAgentWrites: this.agentWrites.size,
    });

    return {
      source: 'user',
    };
  }

  /**
   * Create a workspace event for a file change with proper attribution
   */
  async createFileChangeEvent(
    workspaceId: string,
    changeDetails: ChangeDetails,
    eventType: WorkspaceEventType,
  ): Promise<WorkspaceEvent> {
    try {
      const provenance = await this.attributeChange(changeDetails, workspaceId);

      // Determine actor based on provenance
      let actor: Actor;
      if (provenance.source === 'agent') {
        actor = {
          type: 'agent' as const,
          id: provenance.agent?.id || 'unknown',
          name: provenance.agent?.name || 'Agent',
        };
      } else if (provenance.source === 'system') {
        // System changes are attributed to a special user
        actor = {
          type: 'user' as const,
          id: 'system',
          name: 'System',
          email: 'system@workspace',
        };
      } else {
        actor = {
          type: 'user' as const,
          name: 'User',
          email: 'user@workspace',
        };
      }

      // Create title
      const fileName = changeDetails.filePath?.split('/').pop() || 'file';
      const actionText =
        changeDetails.action === 'create'
          ? 'Created'
          : changeDetails.action === 'delete'
            ? 'Deleted'
            : 'Modified';
      const title = `${actionText} ${fileName}`;

      // Create event
      const event: WorkspaceEvent = {
        id: uuidv4(),
        type: eventType,
        workspaceId: workspaceId as any,
        timestamp: new Date().toISOString(),
        actor,
        title,
        provenance,
        agentId: provenance.agent?.id,
        exchangeId: provenance.chat?.exchangeId,
        codeChange: {
          id: `change-${Date.now()}`,
          fileName,
          filePath: changeDetails.filePath || '',
          type:
            changeDetails.action === 'create'
              ? 'add'
              : changeDetails.action === 'delete'
                ? 'delete'
                : 'modify',
          additions: changeDetails.additions || 0,
          deletions: changeDetails.deletions || 0,
          diff: changeDetails.diff,
          oldContent: changeDetails.oldContent,
          newContent: changeDetails.newContent,
        },
      };

      if (this.debug) {
        logger.info(`[AttributionEngine] Created event for ${changeDetails.filePath}`, {
          eventType,
          source: provenance.source,
          agentName: provenance.agent?.name,
        });
      }

      return event;
    } catch (error) {
      logger.error('[AttributionEngine] Failed to create file change event', {
        workspaceId,
        filePath: changeDetails?.filePath,
        eventType,
        error,
      });
      // Return a minimal event to prevent system failure
      return {
        id: uuidv4(),
        type: eventType,
        workspaceId: workspaceId as any,
        timestamp: new Date().toISOString(),
        actor: {
          type: 'user' as const,
          id: 'system',
          name: 'System',
          email: 'system@workspace',
        },
        title: 'Unknown Change',
        provenance: {
          source: 'system',
        },
      };
    }
  }

  /**
   * Create a workspace event for a generic change with proper attribution
   */
  async createChangeEvent(
    workspaceId: string,
    eventType: WorkspaceEventType,
    title: string,
    options?: {
      description?: string;
      metadata?: Record<string, any>;
    },
  ): Promise<WorkspaceEvent> {
    const provenance = await this.attributeChange({ action: 'modify' }, workspaceId);

    // Determine actor based on provenance
    let actor;
    if (provenance.source === 'agent') {
      actor = {
        type: 'agent' as const,
        id: provenance.agent?.id || 'unknown',
        name: provenance.agent?.name || 'Agent',
      };
    } else if (provenance.source === 'system') {
      actor = {
        type: 'user' as const,
        id: 'system',
        name: 'System',
        email: 'system@workspace',
      };
    } else {
      actor = {
        type: 'user' as const,
        name: 'User',
        email: 'user@workspace',
      };
    }

    const event: WorkspaceEvent = {
      id: uuidv4(),
      type: eventType,
      workspaceId: workspaceId as any,
      timestamp: new Date().toISOString(),
      actor,
      title,
      description: options?.description,
      provenance,
      agentId: provenance.agent?.id,
      exchangeId: provenance.chat?.exchangeId,
      metadata: options?.metadata,
    };

    if (this.debug) {
      logger.info(`[AttributionEngine] Created event: ${title}`, {
        eventType,
        source: provenance.source,
        agentName: provenance.agent?.name,
      });
    }

    return event;
  }

  /**
   * Get the current provenance context
   */
  getCurrentProvenance(): ProvenanceInfo | undefined {
    const context = this.contextManager.getCurrentContext();
    if (!context) return undefined;

    return {
      source: context.source,
      agent: context.agent,
      chat: context.chat,
      execution: context.execution,
    };
  }

  /**
   * Clear all agent writes (useful for testing)
   */
  clearAgentContext(): void {
    this.agentWrites.clear();

    if (this.debug) {
      logger.info('[AttributionEngine] All agent writes cleared');
    }
  }

  /**
   * Get statistics about attribution
   */
  getStats(): {
    hasActiveContext: boolean;
    pendingAgentWrites: number;
    } {
    const hasActiveContext = this.contextManager.getCurrentContext() !== null;

    return {
      hasActiveContext,
      pendingAgentWrites: this.agentWrites.size,
    };
  }

  /**
   * Clean up resources (for testing/shutdown)
   */
  dispose(): void {
    // Clear any pending saves
    for (const timeout of this.pendingSaves.values()) {
      clearTimeout(timeout);
    }
    this.pendingSaves.clear();

    // Clear the cleanup timer if it exists
    if (this.cleanupTimer) {
      clearInterval(this.cleanupTimer);
      this.cleanupTimer = null;
    }

    this.agentWrites.clear();
    this.loadedWorkspaces.clear();
    this.attributionCache.clear();
  }
}

/**
 * Global singleton instance
 */
let globalEngine: AttributionEngine | null = null;

/**
 * Get or create the global attribution engine
 */
export function getAttributionEngine(options?: { debug?: boolean }): AttributionEngine {
  if (!globalEngine) {
    globalEngine = new AttributionEngine(options);
  }
  return globalEngine;
}

/**
 * Reset the global engine (for testing)
 */
export function resetAttributionEngine(): void {
  globalEngine = null;
}
