import { parseUiComponentMetadata } from '../component-metadata';
import { sidebarFixtures } from './sidebar.fixtures';

export const sidebarMetadata = parseUiComponentMetadata({
  id: 'sidebar',
  source: 'src/lib/components/ui/sidebar/index.ts',
  publicImport: '$lib/components/ui/sidebar',
  legacyImports: [],
  exports: [
    'Callout',
    'Content',
    'Footer',
    'Group',
    'GroupAction',
    'GroupActions',
    'GroupContent',
    'GroupLabel',
    'Harness',
    'Header',
    'Input',
    'Inset',
    'Menu',
    'MenuAction',
    'MenuActions',
    'MenuBadge',
    'MenuButton',
    'MenuItem',
    'MenuSkeleton',
    'MenuSub',
    'MenuSubButton',
    'MenuSubItem',
    'Provider',
    'Rail',
    'Root',
    'Separator',
    'Sidebar',
    'SidebarCallout',
    'SidebarContent',
    'SidebarFooter',
    'SidebarGroup',
    'SidebarGroupAction',
    'SidebarGroupActions',
    'SidebarGroupContent',
    'SidebarGroupLabel',
    'SidebarHarness',
    'SidebarHeader',
    'SidebarInput',
    'SidebarInset',
    'SidebarMenu',
    'SidebarMenuAction',
    'SidebarMenuActions',
    'SidebarMenuBadge',
    'SidebarMenuButton',
    'SidebarMenuItem',
    'SidebarMenuSkeleton',
    'SidebarMenuSub',
    'SidebarMenuSubButton',
    'SidebarMenuSubItem',
    'SidebarProvider',
    'SidebarRail',
    'SidebarSeparator',
    'SidebarTrigger',
    'Trigger',
    'sidebarMetadata',
    'useSidebar',
  ],
  category: 'pattern',
  owner: '012-F2',
  callers: [
    'src/lib/component-catalog/renderers/NavigationHelpCatalogPreview.svelte',
    'src/lib/components/file-explorer/file-explorer-layout.svelte',
    'src/lib/components/file-explorer/file-explorer-sidebar.svelte',
  ],
  replacement: null,
  characterizationTest: 'src/lib/components/ui/sidebar/sidebar.test.ts',
  removalGate: 'Retain while host-independent collapsed, mobile, menu, and shortcut tests pass.',
  dynamicImports: [],
  fixtures: sidebarFixtures,
});
