import { parseUiComponentMetadata } from '../component-metadata';
import { inputFixtures } from './input.fixtures';

export const inputMetadata = parseUiComponentMetadata({
  id: 'input',
  source: 'src/lib/components/ui/input/input.svelte',
  publicImport: '$lib/components/ui/input',
  legacyImports: ['$lib/components/ui/input/index.js', '$lib/components/ui/input/input.svelte'],
  exports: ['Input', 'inputMetadata'],
  category: 'primitive',
  owner: '007-B2',
  callers: [
    'src/features/layout/components/content-header/ContentHeader.svelte',
    'src/features/log/components/ActivityLogFilters.svelte',
    'src/features/onboarding/messages/DirectoryPickerView.svelte',
    'src/features/onboarding/messages/GitHubRepoTab.svelte',
    'src/features/onboarding/messages/LocalRepoTab.svelte',
    'src/features/onboarding/messages/NewProjectTab.svelte',
    'src/lib/component-catalog/CatalogGallery.svelte',
    'src/lib/component-catalog/renderers/ContentFieldCatalogPreview.svelte',
    'src/lib/component-catalog/renderers/FieldPreviewCell.svelte',
    'src/lib/component-catalog/renderers/ModalCatalogPreview.svelte',
    'src/lib/component-catalog/renderers/OverlayCatalogPreview.svelte',
    'src/lib/component-catalog/renderers/PopoversCatalogPreview.svelte',
    'src/lib/component-catalog/renderers/ProposalCatalogPreview.svelte',
    'src/lib/components/CommandPalette.svelte',
    'src/lib/components/browser/BrowserOverflowMenu.svelte',
    'src/lib/components/browser/BrowserPanel.svelte',
    'src/lib/components/browser/BrowserViewportMenu.svelte',
    'src/lib/components/browser/EmbeddedBrowser.svelte',
    'src/lib/components/chat/AgentCard.svelte',
    'src/lib/components/chat/ChatMessageNavigator.svelte',
    'src/lib/components/chat/ChatSearch.svelte',
    'src/lib/components/chat/input/ContextPickerButton.svelte',
    'src/lib/components/chat/input/SimpleRichInput.svelte',
    'src/lib/components/chat/proposals/ProposalCard.svelte',
    'src/lib/components/code-review/walkthrough/WalkthroughCommentThread.svelte',
    'src/lib/components/code-review/walkthrough/WalkthroughInlineComment.svelte',
    'src/lib/components/debug/DebugPanel.svelte',
    'src/lib/components/file-explorer/VirtualizedFileTree.svelte',
    'src/lib/components/file-explorer/file-explorer-sidebar.svelte',
    'src/lib/components/layout/ConnectBackendModal.svelte',
    'src/lib/components/layout/panel-system/LayoutPresetDropdown.svelte',
    'src/lib/components/layout/panel-system/PanelLayoutHeader.svelte',
    'src/lib/components/layout/panel-system/PanelTabBar.svelte',
    'src/lib/components/layout/sidebar-nav/cards/ActiveWorkspacesCard.svelte',
    'src/lib/components/layout/sidebar-nav/cards/AllWorkspacesCard.svelte',
    'src/lib/components/modals/FeatureCodeDialog.svelte',
    'src/lib/components/modals/InputDialog.svelte',
    'src/lib/components/patterns/confirm/ConfirmHost.svelte',
    'src/lib/components/patterns/confirm/DestructiveConfirm.svelte',
    'src/lib/components/patterns/settings/SettingsControl.svelte',
    'src/lib/components/patterns/settings/custom-controls.ts',
    'src/lib/components/terminal/QuakeTerminalOverlay.svelte',
    'src/lib/components/terminal/RootQuakeTerminalOverlay.svelte',
    'src/lib/components/terminal/SetupScriptBanner.svelte',
    'src/lib/components/terminal/TerminalSidebar.svelte',
    'src/lib/components/tiptap/BubbleMenu.svelte',
    'src/lib/components/ui/EditableName.svelte',
    'src/lib/components/ui/dropdown/Dropdown.svelte',
    'src/lib/components/ui/message-composer/message-composer.svelte',
    'src/lib/components/ui/panel-find-bar/PanelFindBar.svelte',
    'src/lib/components/ui/searchable-combobox/searchable-combobox.svelte',
    'src/lib/components/ui/sidebar/sidebar-input.svelte',
    'src/lib/components/visualization/ecosystem-visualizer/EcosystemCanvas.svelte',
    'src/lib/components/workspace/CompactWorkspaceInitializer.svelte',
    'src/lib/components/workspace/PullRequestCreator.svelte',
    'src/lib/components/workspace/WorkspaceSidebarHeader.svelte',
    'src/lib/components/workspace/initializer/AddRemoteSetupModal.svelte',
    'src/lib/components/workspace/initializer/BranchSelector.svelte',
    'src/lib/components/workspace/initializer/IssueSuggestions.svelte',
    'src/lib/components/workspace/initializer/RepoSelector.svelte',
    'src/lib/components/workspace/sidebar/BranchDisplay.svelte',
    'src/lib/components/workspace/sidebar/CommitsTimeline.svelte',
    'src/lib/components/workspace/sidebar/NotesPanel.svelte',
    'src/lib/components/workspace/sidebar/PRSection.svelte',
    'src/lib/components/workspace/sidebar/SidebarExpandableSearch.svelte',
    'src/lib/components/workspace/sidebar/WorkspaceProgressCard.svelte',
    'src/lib/components/workspace/sidebar/context-picker/BrowserUrlPicker.svelte',
    'src/lib/components/workspace/sidebar/context-picker/LinearPicker.svelte',
    'src/lib/components/workspace/sidebar/context-picker/SentryPicker.svelte',
    'src/routes/sandbox/recipes/+page.svelte',
  ],
  replacement: null,
  characterizationTest: 'src/lib/components/ui/input/input.test.ts',
  removalGate: 'Retain while exported and binding, focus, validation, and fixture tests pass.',
  dynamicImports: [],
  fixtures: inputFixtures,
});
