import { parseUiComponentMetadata } from '../component-metadata';
import { inputFixtures } from './input.fixtures';

export const inputMetadata = parseUiComponentMetadata({
  id: 'input',
  source: 'src/lib/components/ui/input/input.svelte',
  publicImport: '$lib/components/ui/input',
  legacyImports: ['$lib/components/ui/input/index.js', '$lib/components/ui/input/input.svelte'],
  exports: ['Input', 'inputMetadata'],
  category: 'primitive',
  owner: '007-B2',
  callers: [
    'src/features/new-workspace/ui/SourceCard.svelte',
    'src/lib/component-catalog/CatalogGallery.svelte',
    'src/lib/component-catalog/renderers/ContentFieldCatalogPreview.svelte',
    'src/lib/component-catalog/renderers/OverlayCatalogPreview.svelte',
    'src/lib/component-catalog/renderers/ProposalCatalogPreview.svelte',
    'src/lib/components/browser/BrowserOverflowMenu.svelte',
    'src/lib/components/browser/BrowserPanel.svelte',
    'src/lib/components/browser/BrowserViewportMenu.svelte',
    'src/lib/components/browser/EmbeddedBrowser.svelte',
    'src/lib/components/chat/ChatMessageNavigator.svelte',
    'src/lib/components/chat/input/ContextPickerButton.svelte',
    'src/lib/components/chat/proposals/ProposalCard.svelte',
    'src/lib/components/debug/DebugPanel.svelte',
    'src/lib/components/file-explorer/file-explorer-sidebar.svelte',
    'src/lib/components/layout/ConnectBackendModal.svelte',
    'src/lib/components/layout/panel-system/LayoutPresetDropdown.svelte',
    'src/lib/components/settings/AIBehaviorEditor.svelte',
    'src/lib/components/settings/AgentBackendSettings.svelte',
    'src/lib/components/settings/AgentFeaturesSettings.svelte',
    'src/lib/components/settings/DeviceRow.svelte',
    'src/lib/components/settings/KeyboardShortcutsSettings.svelte',
    'src/lib/components/settings/LinearAuthConnection.svelte',
    'src/lib/components/settings/McpServersSettings.svelte',
    'src/lib/components/settings/SentryAuthConnection.svelte',
    'src/lib/components/settings/VoiceSettings.svelte',
    'src/lib/components/settings/WebSocketApiSettings.svelte',
    'src/lib/components/settings/WorkspaceApiSettings.svelte',
    'src/lib/components/settings/mcp/McpServerForm.svelte',
    'src/lib/components/ui/panel-find-bar/PanelFindBar.svelte',
    'src/lib/components/ui/sidebar/sidebar-input.svelte',
    'src/lib/components/workspace/PullRequestCreator.svelte',
    'src/lib/components/workspace/initializer/AddRemoteSetupModal.svelte',
    'src/lib/components/workspace/initializer/BranchSelector.svelte',
    'src/lib/components/workspace/initializer/RepoSelector.svelte',
    'src/lib/components/workspace/sidebar/SidebarExpandableSearch.svelte',
    'src/lib/components/workspace/sidebar/context-picker/BrowserUrlPicker.svelte',
    'src/lib/components/workspace/sidebar/context-picker/LinearPicker.svelte',
    'src/lib/components/workspace/sidebar/context-picker/SentryPicker.svelte',
  ],
  replacement: null,
  characterizationTest: 'src/lib/components/ui/input/input.test.ts',
  removalGate: 'Retain while exported and binding, focus, validation, and fixture tests pass.',
  dynamicImports: [],
  fixtures: inputFixtures,
});
