import { parseUiComponentMetadata } from '../component-metadata';
import { skeletonFixtures } from './skeleton.fixtures';

export const skeletonMetadata = parseUiComponentMetadata({
  id: 'skeleton',
  source: 'src/lib/components/ui/skeleton/skeleton.svelte',
  publicImport: '$lib/components/ui/skeleton',
  legacyImports: [
    '$lib/components/ui/skeleton/index.js',
    '$lib/components/ui/skeleton/skeleton.svelte',
  ],
  exports: ['Root', 'Skeleton', 'skeletonMetadata'],
  category: 'primitive',
  owner: '007-B1',
  callers: [
    'src/features/file-tracking/components/diff/TrackedChangeDiffViewer.svelte',
    'src/features/layout/tab-types/FileTabType.svelte',
    'src/features/layout/tab-types/NoteTabType.svelte',
    'src/features/log/components/ActivityTimeline.svelte',
    'src/lib/component-catalog/renderers/ContentFieldCatalogPreview.svelte',
    'src/lib/components/CommandPalette.svelte',
    'src/lib/components/chat/ChatChangesPanel.svelte',
    'src/lib/components/chat/ChatPanel.svelte',
    'src/lib/components/code-review/CodeReviewPanel.svelte',
    'src/lib/components/code-review/CodeReviewTabContent.svelte',
    'src/lib/components/file-explorer/file-tree-view.svelte',
    'src/lib/components/layout/sidebar-nav/WorkspaceCardSkeleton.svelte',
    'src/lib/components/notes/NotesPanel.svelte',
    'src/lib/components/notes/primitives/ReferenceBlock.svelte',
    'src/lib/components/settings/McpServersSettings.svelte',
    'src/lib/components/terminal/TerminalSidebar.svelte',
    'src/lib/components/ui/sidebar/sidebar-menu-skeleton.svelte',
    'src/lib/components/ui/tooltip/GitHubLinkCard.svelte',
    'src/lib/components/workspace/CheckoutModePill.svelte',
    'src/lib/components/workspace/ContentSkeleton.svelte',
    'src/lib/components/workspace/NoteWithComments.svelte',
    'src/lib/components/workspace/PullRequestCreator.svelte',
    'src/lib/components/workspace/SidebarSkeleton.svelte',
    'src/lib/components/workspace/WorkspaceAgentsList.svelte',
    'src/lib/components/workspace/WorkspaceHoverCard.svelte',
    'src/lib/components/workspace/initializer/IssueSuggestions.svelte',
    'src/lib/components/workspace/sidebar/CodeChangesPanel.svelte',
    'src/lib/components/workspace/sidebar/NotesPanel.svelte',
    'src/lib/components/workspace/sidebar/SecondaryRootChangesView.svelte',
    'src/lib/components/workspace/sidebar/SidebarActivityPanel.svelte',
    'src/lib/components/workspace/sidebar/SidebarChangesPanel.svelte',
  ],
  replacement: null,
  characterizationTest: 'src/lib/components/ui/skeleton/skeleton.test.ts',
  removalGate: 'Retain while exported and loading, reduced-motion, and fixture tests pass.',
  dynamicImports: [],
  fixtures: skeletonFixtures,
});
