import type { UiComponentFixture } from '../component-metadata';

export const sliderFixtures = [
  {
    id: 'slider-state-matrix',
    title: 'Slider interaction states',
    states: [
      'default',
      'disabled',
      'invalid',
      'keyboard-focus',
      'arrow-keys',
      'home-end',
      'hover-preview',
      'hover-tooltip',
      'drag-tooltip-hidden',
      'synchronous-drag',
      'spring-settle',
      'inline-value-edit',
      'discrete-steps',
      'step-pips',
      'semantic-track',
      'semantic-thumb',
      'transparent-overlay-track',
      'compact',
      'light',
      'dark',
      'reduced-motion',
      'zoom-200',
      'no-overflow',
      'capture-hover-drag-200ms',
    ],
    themes: ['light', 'dark'],
    viewport: 'both',
    reducedMotion: true,
  },
] satisfies UiComponentFixture[];
