<script lang="ts">
  /**
   * CodeReviewTabContent - Self-contained code review component for panel tabs
   * Includes its own executor and renders without a header wrapper
   */

  import { workspaceStore } from '$features/workspace/workspace.store.svelte';
  import { fileTrackingStore } from '$features/file-tracking/file-tracking.store.svelte';
  import {
    createCodeReviewExecutor,
    createWalkthroughExecutor,
  } from '$features/agent/background-agent-executor.svelte';
  import { extractTextFromBlocks } from '$lib/utils/text-utils';
  import { createLogger } from '$lib/utils/client-logger';
  import { toast } from 'svelte-sonner';
  import type { ReviewStatus } from './types';
  import { CodeWalkthroughSection, parseWalkthrough } from './walkthrough';
  import type { CodeWalkthrough, WalkthroughStatus } from './walkthrough';
  import Fa from 'svelte-fa';
  import {
    faWandMagicSparkles,
    faSpinner,
    faStop,
    faRotateRight,
    faCheck,
  } from '@fortawesome/free-solid-svg-icons';
  import { Button } from '$lib/components/ui/button';
  import { Badge } from '$lib/components/ui/badge';
  import { Skeleton } from '$lib/components/ui/skeleton';
  import MarkdownViewer from '$lib/components/markdown/MarkdownViewer.svelte';
  import { fly } from 'svelte/transition';

  const logger = createLogger('CodeReviewTabContent');

  interface Props {
    workspaceId: string;
  }

  let { workspaceId: _workspaceId }: Props = $props();

  // Get workspace and staged files
  const workspace = $derived(workspaceStore.current);
  const stagedFiles = $derived(fileTrackingStore.workingChanges.staged);
  const workspacePath = $derived(workspace?.worktreePath || workspace?.repositoryPath || '');

  // Review state
  let status = $state<ReviewStatus>('idle');
  let result = $state<string | null>(null);
  let streamingText = $state('');
  let error = $state('');

  // Walkthrough state
  let walkthrough = $state<CodeWalkthrough | null>(null);
  let walkthroughStatus = $state<WalkthroughStatus>('idle');
  let walkthroughError = $state('');
  let hasAutoGeneratedWalkthrough = $state(false);

  // Code review executor
  const codeReviewExecutor = createCodeReviewExecutor({
    onMessage: (message) => {
      const text = extractTextFromBlocks(message.contentBlocks || []);
      streamingText = text;
      status = 'running';
    },
    onResult: (resultText) => {
      logger.info('Code review completed', { resultLength: resultText.length });
      result = resultText;
      status = 'complete';
      toast.success('Code review complete');
    },
    onError: (err) => {
      error = err.message;
      status = 'error';
      toast.error(`Review failed: ${err.message}`);
    },
    onStatusChange: () => {},
  });

  // Walkthrough executor
  const walkthroughExecutor = createWalkthroughExecutor({
    onResult: (resultText) => {
      const parsed = parseWalkthrough(resultText);
      if (parsed) {
        walkthrough = parsed;
        walkthroughStatus = 'complete';
      } else {
        walkthroughError = 'Failed to parse walkthrough';
        walkthroughStatus = 'error';
      }
    },
    onError: (err) => {
      walkthroughError = err.message;
      walkthroughStatus = 'error';
    },
    onStatusChange: (newStatus) => {
      if (newStatus === 'running') {
        walkthroughStatus = 'running';
        walkthroughError = '';
      } else if (newStatus === 'cancelled') {
        walkthroughStatus = 'idle';
      }
    },
  });

  // Derived states
  const isRunning = $derived(status === 'running');
  const isComplete = $derived(status === 'complete');
  const hasChanges = $derived(stagedFiles.length > 0);

  // Auto-generate walkthrough when review completes
  $effect(() => {
    if (
      isComplete &&
      !walkthrough &&
      walkthroughStatus === 'idle' &&
      !hasAutoGeneratedWalkthrough
    ) {
      hasAutoGeneratedWalkthrough = true;
      handleGenerateWalkthrough();
    }
  });

  async function handleTriggerReview() {
    if (!workspace) return;

    status = 'running';
    result = null;
    streamingText = '';
    error = '';

    await codeReviewExecutor.execute(workspace, {
      files: stagedFiles.map((f) => f.relativePath),
    });
  }

  function handleStop() {
    codeReviewExecutor.cancel();
    status = 'idle';
  }

  async function handleGenerateWalkthrough() {
    if (!workspace) return;
    walkthroughStatus = 'running';
    walkthroughError = '';
    walkthrough = null;
    await walkthroughExecutor.execute(workspace);
  }
</script>

<div class="flex flex-col h-full overflow-auto">
  <!-- Content area -->
  <div class="flex-1 overflow-auto p-4">
    <!-- Empty state -->
    {#if status === 'idle' && !result && !walkthrough}
      <div class="flex flex-col items-center justify-center py-16 px-8 text-center">
        <div
          class="w-12 h-12 rounded-full bg-muted/50 flex items-center justify-center mb-4"
          transition:fly={{ y: 8, duration: 200 }}
        >
          <Fa icon={faWandMagicSparkles} class="h-5 w-5 text-subtle" />
        </div>
        <h3 class="text-sm font-medium text-foreground mb-2">Review Your Changes</h3>
        <p class="text-xs text-subtle mb-4 max-w-60">
          {#if hasChanges}
            Get AI-powered feedback on your {stagedFiles.length} staged file{stagedFiles.length ===
            1
              ? ''
              : 's'}.
          {:else}
            Stage some changes to get started with a code review.
          {/if}
        </p>
        {#if hasChanges}
          <Button variant="default" size="sm" onclick={handleTriggerReview}>
            <Fa icon={faWandMagicSparkles} class="h-4 w-4 mr-2" />
            Start Review
          </Button>
        {/if}
      </div>
    {:else if isRunning}
      <!-- Running state -->
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-2">
            <Fa icon={faSpinner} class="h-4 w-4 animate-spin text-primary" />
            <span class="text-sm font-medium">Reviewing your changes...</span>
          </div>
          <Button variant="ghost" size="xs" onclick={handleStop}>
            <Fa icon={faStop} class="h-3 w-3 mr-1" />
            Stop
          </Button>
        </div>
        {#if streamingText}
          <div class="text-sm text-subtle">
            <MarkdownViewer content={streamingText} isStreaming />
          </div>
        {:else}
          <div class="space-y-3">
            <Skeleton class="h-4 w-full" />
            <Skeleton class="h-4 w-3/4" />
            <Skeleton class="h-4 w-1/2" />
          </div>
        {/if}
      </div>
    {:else if isComplete || walkthrough || walkthroughStatus !== 'idle'}
      <!-- Completed state with walkthrough -->
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-2">
            <Badge
              variant="default"
              class="text-xs gap-1 bg-green-500/10 text-green-600 border-green-500/20"
            >
              <Fa icon={faCheck} class="h-3 w-3" />
              Review Complete
            </Badge>
          </div>
          <Button variant="ghost" size="xs" onclick={handleTriggerReview}>
            <Fa icon={faRotateRight} class="h-3 w-3 mr-1" />
            Re-review
          </Button>
        </div>

        <!-- Walkthrough section -->
        <CodeWalkthroughSection
          {walkthrough}
          {workspacePath}
          changes={stagedFiles}
          status={walkthroughStatus}
          error={walkthroughError}
          onRegenerate={handleGenerateWalkthrough}
        />
      </div>
    {:else if error}
      <!-- Error state -->
      <div class="flex flex-col items-center justify-center py-8 text-center">
        <p class="text-sm text-red-500 mb-4">{error}</p>
        <Button variant="outline" size="sm" onclick={handleTriggerReview}>
          <Fa icon={faRotateRight} class="h-4 w-4 mr-2" />
          Try Again
        </Button>
      </div>
    {/if}
  </div>
</div>
