<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import { Badge } from '$lib/components/ui/badge';
  import { Skeleton } from '$lib/components/ui/skeleton';
  import PanelWrapper from '$lib/components/ui/PanelWrapper.svelte';
  import Fa from 'svelte-fa';
  import {
    faRotateRight,
    faStop,
    faCheck,
    faSpinner,
    faRobot,
    faCodeCompare,
    faChevronLeft,
    faChevronRight,
    faWandMagicSparkles,
  } from '@fortawesome/free-solid-svg-icons';
  import { fly } from 'svelte/transition';
  import ReviewCommentCard from './ReviewCommentCard.svelte';
  import type { ReviewComment, ReviewStatus, ReviewSeverity, CodeReview } from './types';
  import { parseAllReviewComments, parseReviewSummary } from './types';
  import type { TrackedChange } from '$features/file-tracking/types';
  import { workspaceStore } from '$features/workspace/workspace.store.svelte';
  import MarkdownViewer from '$lib/components/markdown/MarkdownViewer.svelte';
  import { CodeWalkthroughSection, parseWalkthrough } from './walkthrough';
  import type { CodeWalkthrough, WalkthroughStatus } from './walkthrough';
  import { createWalkthroughExecutor } from '$features/agent/background-agent-executor.svelte';
  import { createLogger } from '$lib/utils/client-logger';
  import { getTransientUIStore } from '$features/workspace/transient-ui-state.store.svelte';
  import { agentService } from '$features/agent/agent.service';
  import { buildWorkspaceContext } from '$features/agent/agent-launch-core';

  const logger = createLogger('CodeReviewPanel');

  // Get transient store for persistence
  function getTransientStore() {
    const workspace = workspaceStore.current;
    return workspace ? getTransientUIStore(workspace.id) : null;
  }

  // Review archive item type
  interface ReviewArchiveItem {
    result: string | null;
    agentId: string | null;
    stagedFiles: string[];
    status: ReviewStatus;
    timestamp: number;
  }

  interface Props {
    review: CodeReview | null;
    status: ReviewStatus;
    streamingText?: string;
    result?: string;
    error?: string;
    agentId?: string;
    changes?: TrackedChange[];
    canGoBack?: boolean;
    canGoForward?: boolean;
    onNavigateBack?: () => void;
    onNavigateForward?: () => void;
    onStop?: () => void;
    onRerun?: () => void;
    onTriggerReview?: () => void;
    onViewInDiff?: (comment: ReviewComment) => void;
    onFix?: (comment: ReviewComment) => void;
    onOpenAgent?: (agentId: string) => void;
    onNavigateToChanges?: () => void;
    /** Review history for version navigation */
    reviewArchive?: ReviewArchiveItem[];
    /** Current review index in archive (0 = current/newest) */
    currentReviewIndex?: number;
    /** Navigate to a specific review in the archive */
    onSelectReview?: (index: number) => void;
  }

  let {
    review,
    status,
    streamingText = '',
    result = '',
    error = '',
    agentId,
    changes = [],
    canGoBack = false,
    canGoForward = false,
    onNavigateBack,
    onNavigateForward,
    onStop,
    onRerun,
    onTriggerReview,
    onViewInDiff,
    onFix,
    onOpenAgent,
    onNavigateToChanges,
    reviewArchive = [],
    currentReviewIndex = 0,
    onSelectReview,
  }: Props = $props();

  // Version history navigation helpers
  const hasMultipleVersions = $derived(reviewArchive.length > 1);
  const canGoPrev = $derived(currentReviewIndex < reviewArchive.length - 1);
  const canGoNext = $derived(currentReviewIndex > 0);
  const currentVersionLabel = $derived(
    currentReviewIndex === 0
      ? 'Current'
      : `Review ${reviewArchive.length - currentReviewIndex}/${reviewArchive.length}`,
  );

  // Open agent in panel
  function handleOpenAgent() {
    if (agentId) {
      if (onOpenAgent) {
        onOpenAgent(agentId);
      } else {
        // Fallback to dispatching event (use workspace:open-agent for panel layout support)
        window.dispatchEvent(new CustomEvent('workspace:open-agent', { detail: { agentId } }));
      }
    }
  }

  // Filter state
  let severityFilter = $state<ReviewSeverity | 'all'>('all');
  let showDismissed = $state(false);

  // Get workspace path for loading code snippets
  const workspacePath = $derived(
    workspaceStore.current?.worktreePath || workspaceStore.current?.repositoryPath,
  );

  // Walkthrough state
  let walkthrough = $state<CodeWalkthrough | null>(null);
  let walkthroughStatus = $state<WalkthroughStatus>('idle');
  let walkthroughError = $state('');

  // Auto-generate flag and load flag (defined before effects that use them)
  let hasAutoGeneratedWalkthrough = $state(false);
  let hasLoadedFromStore = false;

  // Walkthrough executor with persistence
  const walkthroughExecutor = createWalkthroughExecutor({
    onResult: (resultText) => {
      const parsed = parseWalkthrough(resultText);
      if (parsed) {
        walkthrough = parsed;
        walkthroughStatus = 'complete';
      } else {
        walkthroughError = 'Failed to parse walkthrough';
        walkthroughStatus = 'error';
      }
      // Persist state
      getTransientStore()?.setWalkthroughExecutorState(walkthroughExecutor.getState());
    },
    onError: (err) => {
      walkthroughError = err.message;
      walkthroughStatus = 'error';
      // Persist state
      getTransientStore()?.setWalkthroughExecutorState(walkthroughExecutor.getState());
    },
    onStatusChange: (newStatus) => {
      if (newStatus === 'running') {
        walkthroughStatus = 'running';
        walkthroughError = '';
      } else if (newStatus === 'cancelled') {
        walkthroughStatus = 'idle';
      }
      // Persist state on any change
      getTransientStore()?.setWalkthroughExecutorState(walkthroughExecutor.getState());
    },
  });

  // Load persisted walkthrough on mount (only once)
  $effect(() => {
    if (hasLoadedFromStore) return;

    const store = getTransientStore();
    if (!store) return;

    hasLoadedFromStore = true;
    const savedState = store.acceptChanges.walkthroughExecutor;
    if (savedState?.result) {
      // Parse the saved result
      const parsed = parseWalkthrough(savedState.result);
      if (parsed) {
        walkthrough = parsed;
        walkthroughStatus = 'complete';
        hasAutoGeneratedWalkthrough = true;
        logger.info('Loaded persisted walkthrough');
      }
    }
  });

  async function handleGenerateWalkthrough() {
    const workspace = workspaceStore.current;
    if (!workspace) return;

    walkthroughStatus = 'running';
    walkthroughError = '';
    walkthrough = null;

    await walkthroughExecutor.execute(workspace);
  }

  // State for sending walkthrough messages
  let isSendingWalkthroughMessage = $state(false);

  /**
   * Handle sending a message about a specific line in the walkthrough
   * This sends the message to the review agent with context about the file and line
   */
  async function handleWalkthroughMessage(message: string, lineNumber: number, fileName: string) {
    const workspace = workspaceStore.current;
    if (!workspace || !agentId) {
      logger.warn('Cannot send walkthrough message: no workspace or agent');
      return;
    }

    isSendingWalkthroughMessage = true;

    try {
      // Build context with file and line information
      const workspacePath = workspace.worktreePath || workspace.repositoryPath || '';
      const contextMessage = `[Question about ${fileName}:${lineNumber}]\n\n${message}`;

      // Build workspace context for STDIN
      const stdinContext = buildWorkspaceContext(workspacePath, [
        {
          type: 'file',
          filePath: fileName,
          lineNumber: lineNumber,
        },
      ]);

      await agentService.sendMessage(agentId, contextMessage, workspace, {
        stdinContext,
      });

      logger.info('Walkthrough message sent successfully', { fileName, lineNumber });
    } catch (error) {
      logger.error('Failed to send walkthrough message', error);
    } finally {
      isSendingWalkthroughMessage = false;
    }
  }

  // Derived state
  const isRunning = $derived(status === 'running');
  const isComplete = $derived(status === 'complete');
  const isStale = $derived(status === 'stale');
  const hasError = $derived(status === 'error');

  // Auto-generate walkthrough when code review completes
  $effect(() => {
    if (
      isComplete &&
      !walkthrough &&
      walkthroughStatus === 'idle' &&
      !hasAutoGeneratedWalkthrough
    ) {
      hasAutoGeneratedWalkthrough = true;
      handleGenerateWalkthrough();
    }
  });

  // Parse comments from result if review.comments is empty
  // This handles the case where the result string contains the review but hasn't been parsed yet
  const comments = $derived.by(() => {
    // First try to use comments from the review object
    if (review?.comments && review.comments.length > 0) {
      return review.comments;
    }
    // If no comments in review but we have a result, parse it
    if (result && isComplete) {
      const parsed = parseAllReviewComments(result);
      return parsed;
    }
    return [];
  });

  const filteredComments = $derived(
    comments.filter((c) => {
      if (!showDismissed && c.dismissed) return false;
      if (severityFilter !== 'all' && c.severity !== severityFilter) return false;
      return true;
    }),
  );

  const severityCounts = $derived({
    critical: comments.filter((c) => c.severity === 'critical' && !c.dismissed).length,
    important: comments.filter((c) => c.severity === 'important' && !c.dismissed).length,
    minor: comments.filter((c) => c.severity === 'minor' && !c.dismissed).length,
  });

  const totalCount = $derived(comments.filter((c) => !c.dismissed).length);

  // Get last 3 meaningful lines from streaming text for preview
  const streamingPreview = $derived.by(() => {
    if (!streamingText) return '';
    const lines = streamingText
      .split('\n')
      .filter((l) => l.trim().length > 0)
      .slice(-3);
    return lines.join('\n');
  });

  // Summary to display (final result when complete)
  // Parse the summary from the result JSON, falling back to review.summary
  const displaySummary = $derived.by(() => {
    if (!isComplete) return null;
    // Try to parse summary from result first
    if (result) {
      const parsed = parseReviewSummary(result);
      if (parsed) return parsed;
    }
    // Fall back to review.summary
    return review?.summary || null;
  });
</script>

<PanelWrapper
  title="Code Review"
  breadcrumbs={[{ label: 'Changes', icon: faCodeCompare, onClick: onNavigateToChanges }]}
  {canGoBack}
  {canGoForward}
  {onNavigateBack}
  {onNavigateForward}
  contentClass="flex-1 overflow-auto"
>
  {#snippet actions()}
    <div class="flex items-center gap-2">
      <!-- Version navigation (only show if multiple versions) -->
      {#if hasMultipleVersions}
        <div class="flex items-center gap-1 mr-2">
          <Button
            variant="ghost"
            size="icon-xs"
            onclick={() => onSelectReview?.(currentReviewIndex + 1)}
            disabled={!canGoPrev}
            class="h-6 w-6"
          >
            <Fa icon={faChevronLeft} class="h-3 w-3" />
          </Button>
          <span class="text-xs text-muted-foreground min-w-15 text-center">
            {currentVersionLabel}
          </span>
          <Button
            variant="ghost"
            size="icon-xs"
            onclick={() => onSelectReview?.(currentReviewIndex - 1)}
            disabled={!canGoNext}
            class="h-6 w-6"
          >
            <Fa icon={faChevronRight} class="h-3 w-3" />
          </Button>
        </div>
      {/if}

      <!-- Status badges -->
      {#if isRunning}
        <Badge variant="secondary" class="text-xs gap-1">
          <Fa icon={faSpinner} class="h-3 w-3 animate-spin" />
          Reviewing...
        </Badge>
      {:else if isComplete && totalCount === 0}
        <Badge
          variant="default"
          class="text-xs gap-1 bg-green-500/10 text-green-600 border-green-500/20"
        >
          <Fa icon={faCheck} class="h-3 w-3" />
          Looks good
        </Badge>
      {:else if isComplete && totalCount > 0}
        <Badge variant="secondary" class="text-xs">
          {totalCount} comment{totalCount === 1 ? '' : 's'}
        </Badge>
      {:else if isStale}
        <Badge variant="outline" class="text-xs text-amber-600">Outdated</Badge>
      {/if}

      <!-- Action buttons -->
      {#if isRunning && onStop}
        <Button variant="ghost" size="xs" onclick={onStop}>
          <Fa icon={faStop} class="h-3 w-3 mr-1" />
          Stop
        </Button>
      {:else if status === 'idle' && onTriggerReview}
        <Button variant="default" size="xs" onclick={onTriggerReview}>
          <Fa icon={faWandMagicSparkles} class="h-3 w-3 mr-1" />
          Review
        </Button>
      {:else if (isComplete || isStale) && onRerun}
        <Button variant="ghost" size="xs" onclick={onRerun}>
          <Fa icon={faRotateRight} class="h-3 w-3 mr-1" />
          Re-review
        </Button>
      {/if}
    </div>
  {/snippet}

  <!-- Empty state (no review yet) -->
  {#if status === 'idle' && !result && !walkthrough}
    <div class="flex flex-col items-center justify-center py-16 px-8 text-center">
      <div
        class="w-12 h-12 rounded-full bg-muted/50 flex items-center justify-center mb-4"
        transition:fly={{ y: 8, duration: 200 }}
      >
        <Fa icon={faWandMagicSparkles} class="h-5 w-5 text-muted-foreground" />
      </div>
      <h3 class="text-sm font-medium text-foreground mb-2">No review yet</h3>
      <p class="text-xs text-muted-foreground mb-4 max-w-60">
        Run a code review to get AI-powered feedback on your staged changes.
      </p>
      {#if onTriggerReview}
        <Button variant="default" size="sm" onclick={onTriggerReview}>
          <Fa icon={faWandMagicSparkles} class="h-3 w-3 mr-1.5" />
          Review Changes
        </Button>
      {/if}
    </div>
  {:else}
    <!-- Agent Status Card (shows while running) -->
    {#if isRunning}
      <div class="p-4 border-b border-border" transition:fly={{ y: 4, duration: 200 }}>
        <div class="rounded-lg border border-border bg-muted/30 p-3">
          <div class="flex items-center justify-between mb-2">
            <div class="flex items-center gap-2">
              <div class="w-2 h-2 rounded-full bg-blue-500 animate-pulse"></div>
              <span class="text-sm font-medium text-foreground">Reviewing code...</span>
            </div>
            {#if agentId}
              <Button
                variant="ghost"
                size="xs"
                class="text-xs h-6 text-muted-foreground hover:text-foreground"
                onclick={handleOpenAgent}
              >
                <Fa icon={faRobot} class="h-3 w-3 mr-1" />
                View Agent
              </Button>
            {/if}
          </div>
          {#if streamingPreview}
            <div
              class="text-xs text-muted-foreground whitespace-pre-wrap line-clamp-3 overflow-hidden"
            >
              {streamingPreview}
              <span
                class="inline-block w-1.5 h-3 bg-muted-foreground/50 animate-pulse ml-0.5 align-middle"
              ></span>
            </div>
          {:else}
            <div class="text-xs text-muted-foreground">Analyzing staged changes...</div>
          {/if}
        </div>
      </div>
    {/if}

    <!-- Error Card (shows when error) -->
    {#if hasError && error}
      <div class="p-4 border-b border-border" transition:fly={{ y: 4, duration: 200 }}>
        <div
          class="rounded-lg border border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-950/30 p-3"
        >
          <div class="flex items-center gap-2 text-sm text-red-600 dark:text-red-400">
            <span class="font-medium">Review failed:</span>
            <span>{error}</span>
          </div>
          {#if onRerun}
            <Button
              variant="ghost"
              size="xs"
              class="mt-2 text-red-600 dark:text-red-400"
              onclick={onRerun}
            >
              <Fa icon={faRotateRight} class="h-3 w-3 mr-1" />
              Try again
            </Button>
          {/if}
        </div>
      </div>
    {/if}

    <!-- Code Walkthrough Section (shown first as main content) -->
    {#if isComplete || walkthrough || walkthroughStatus !== 'idle'}
      <CodeWalkthroughSection
        {walkthrough}
        {workspacePath}
        {changes}
        status={walkthroughStatus}
        error={walkthroughError}
        onRegenerate={handleGenerateWalkthrough}
        onSendMessage={handleWalkthroughMessage}
        isSending={isSendingWalkthroughMessage}
      />
    {:else if isRunning}
      <!-- Walkthrough skeleton while loading -->
      <div class="p-5 border-b border-border">
        <div class="flex items-center gap-2 mb-4">
          <Skeleton class="h-5 w-5 rounded" />
          <Skeleton class="h-5 w-32" />
        </div>
        <div class="space-y-3">
          <Skeleton class="h-4 w-full" />
          <Skeleton class="h-4 w-5/6" />
          <Skeleton class="h-4 w-4/5" />
        </div>
        <div class="mt-4 space-y-2">
          {#each [1, 2] as i (i)}
            <div class="flex items-start gap-3 p-3 rounded-lg bg-muted/30">
              <Skeleton class="h-4 w-4 rounded mt-0.5" />
              <div class="flex-1 space-y-2">
                <Skeleton class="h-4 w-24" />
                <Skeleton class="h-3 w-full" />
              </div>
            </div>
          {/each}
        </div>
      </div>
    {/if}

    <!-- Summary Card (shows when complete) -->
    {#if !isRunning && !hasError && displaySummary}
      <div class="pt-5 px-5">
        <div class="text-sm text-muted-foreground" transition:fly={{ y: 4, duration: 200 }}>
          <MarkdownViewer content={displaySummary} className="prose-sm" />
        </div>
      </div>
    {/if}

    <!-- Review Comments Section -->
    {#if filteredComments.length > 0 || isRunning}
      <div class="px-5 pt-4 pb-2">
        <h3 class="text-sm font-medium text-foreground flex items-center gap-2">
          Review Comments
          {#if totalCount > 0}
            <Badge variant="secondary" class="text-xs">{totalCount}</Badge>
          {/if}
        </h3>
      </div>
      <div class="space-y-4 mx-5 mb-5">
        {#if isRunning && comments.length === 0}
          <!-- Loading skeletons (GitHub-style card) -->
          {#each [1, 2] as i (i)}
            <div
              class="rounded-lg border border-border bg-card shadow-sm overflow-hidden"
              transition:fly={{ y: 8, duration: 200, delay: i * 100 }}
            >
              <!-- Header skeleton -->
              <div class="flex items-center gap-3 px-4 py-3 border-b border-border/50">
                <Skeleton class="h-8 w-8 rounded-full" />
                <div class="flex-1 space-y-1">
                  <Skeleton class="h-4 w-32" />
                </div>
              </div>
              <!-- Content skeleton -->
              <div class="p-4 space-y-3">
                <Skeleton class="h-4 w-3/4" />
                <Skeleton class="h-3 w-full" />
                <Skeleton class="h-3 w-5/6" />
              </div>
              <!-- Footer skeleton -->
              <div class="px-4 py-2 border-t border-border/50">
                <Skeleton class="h-6 w-20" />
              </div>
            </div>
          {/each}
        {:else}
          <!-- Linear list of comments (GitHub-style cards) -->
          {#each filteredComments as comment, i (comment.id)}
            <div transition:fly={{ y: 8, duration: 200, delay: Math.min(i * 30, 300) }}>
              <ReviewCommentCard
                {comment}
                {workspacePath}
                {onViewInDiff}
                {onFix}
                class="border border-border"
              />
            </div>
          {/each}
        {/if}
      </div>
    {:else if isComplete && totalCount === 0}
      <!-- No issues found message -->
      <div class="px-5 py-4">
        <div class="flex items-center gap-2 text-sm text-green-600">
          <Fa icon={faCheck} class="h-4 w-4" />
          No issues found - your code looks good!
        </div>
      </div>
    {/if}
  {/if}
</PanelWrapper>
