<script lang="ts">
  /**
   * CodeReviewTabContent - Self-contained code review component for panel tabs
   * Includes its own executor and renders without a header wrapper
   */

  import { selectActiveWorkspace } from '$store/renderer/slices/workspace/workspace-selectors';
  import { selectCurrentStagedWorkingChanges } from '$store/renderer/slices/changes/changes-selectors';

  import { selectExecutorState } from '$store/renderer/slices/background-agent-executor/background-agent-executor-selectors';
  import {
  executeBackgroundAgent,
  cancelExecution,
} from '$store/renderer/slices/background-agent-executor/background-agent-executor-slice';
  import type { ReviewStatus } from './types';
  import {
  CodeWalkthroughSection,
  parseWalkthrough,
} from './walkthrough';
  import type { CodeWalkthrough, WalkthroughStatus } from './walkthrough';
  import Fa from 'svelte-fa';
  import {
  faWandMagicSparkles,
  faSpinner,
  faStop,
  faRotateRight,
  faCheck,
} from '@fortawesome/free-solid-svg-icons';
  import { Button } from '$lib/components/ui/button';
  import { Badge } from '$lib/components/ui/badge';
  import { Skeleton } from '$lib/components/ui/skeleton';
  import MarkdownViewer from '$lib/components/markdown/MarkdownViewer.svelte';
  import { fly } from 'svelte/transition';
  import { store as appStore } from '$store/renderer/store';
  import * as m from '$shared/paraglide/messages.js';


  interface Props {
    workspaceId: string;
  }

  let { workspaceId }: Props = $props();


  // Get workspace and staged files
  const activeWorkspace = selectActiveWorkspace();
  const workspace = $derived($activeWorkspace);
  const ftStagedChanges$ = selectCurrentStagedWorkingChanges();
  const workspacePath = $derived(workspace?.worktreePath || workspace?.repositoryPath || '');

  // Review state
  let status = $state<ReviewStatus>('idle');
  let result = $state<string | null>(null);
  let streamingText = $state('');
  let error = $state('');

  // Walkthrough state
  let walkthrough = $state<CodeWalkthrough | null>(null);
  let walkthroughStatus = $state<WalkthroughStatus>('idle');
  let walkthroughError = $state('');
  let hasAutoGeneratedWalkthrough = $state(false);

  // Code review executor state from Redux
  const reviewExecState$ = selectExecutorState(workspaceId, 'review');
  const walkthroughExecState$ = selectExecutorState(workspaceId, 'walkthrough');

  // Sync Redux state to local UI state
  $effect(() => {
    const state = $reviewExecState$;
    if (state.status === 'running' || state.status === 'initializing') {
      status = 'running';
    } else if (state.status === 'success' && state.result) {
      result = state.result;
      status = 'complete';
    } else if (state.status === 'error' && state.error) {
      error = state.error;
      status = 'error';
    }
  });

  $effect(() => {
    const state = $walkthroughExecState$;
    if (state.status === 'running' || state.status === 'initializing') {
      walkthroughStatus = 'running';
      walkthroughError = '';
    } else if (state.status === 'success' && state.result) {
      const parsed = parseWalkthrough(state.result);
      if (parsed) {
        walkthrough = parsed;
        walkthroughStatus = 'complete';
      } else {
        walkthroughError = m.codeReview_walkthrough_parseFailed_error();
        walkthroughStatus = 'error';
      }
    } else if (state.status === 'error' && state.error) {
      walkthroughError = state.error;
      walkthroughStatus = 'error';
    } else if (state.status === 'cancelled') {
      walkthroughStatus = 'idle';
    }
  });

  // Derived states
  const isRunning = $derived(status === 'running');
  const isComplete = $derived(status === 'complete');
  const hasChanges = $derived($ftStagedChanges$.length > 0);

  // Auto-generate walkthrough when review completes
  $effect(() => {
    if (
      isComplete &&
      !walkthrough &&
      walkthroughStatus === 'idle' &&
      !hasAutoGeneratedWalkthrough
    ) {
      hasAutoGeneratedWalkthrough = true;
      handleGenerateWalkthrough();
    }
  });

  function handleTriggerReview() {
    if (!workspace) return;

    status = 'running';
    result = null;
    streamingText = '';
    error = '';

    appStore.dispatch(executeBackgroundAgent(workspaceId, 'review', {
      files: $ftStagedChanges$.map((f) => f.relativePath),
    }));
  }

  function handleStop() {
    appStore.dispatch(cancelExecution(workspaceId, 'review'));
    status = 'idle';
  }

  function handleGenerateWalkthrough() {
    if (!workspace) return;
    walkthroughStatus = 'running';
    walkthroughError = '';
    walkthrough = null;
    appStore.dispatch(executeBackgroundAgent(workspaceId, 'walkthrough'));
  }
</script>

<div class="flex flex-col h-full overflow-auto">
  <!-- Content area -->
  <div class="flex-1 overflow-auto p-4">
    <!-- Empty state -->
    {#if status === 'idle' && !result && !walkthrough}
      <div class="flex flex-col items-center justify-center py-16 px-8 text-center">
        <div
          class="w-12 h-12 rounded-full bg-muted/50 flex items-center justify-center mb-4"
          transition:fly={{ y: 8, duration: 200 }}
        >
          <Fa icon={faWandMagicSparkles} class="h-5 w-5 text-subtle" />
        </div>
        <h3 class="text-sm font-medium text-foreground mb-2">{m.codeReview_tabContent_reviewYourChanges_title()}</h3>
        <p class="text-xs text-subtle mb-4 max-w-60">
          {#if hasChanges}
            {$ftStagedChanges$.length === 1
              ? m.codeReview_tabContent_stagedFeedback_one({ count: $ftStagedChanges$.length })
              : m.codeReview_tabContent_stagedFeedback_many({ count: $ftStagedChanges$.length })}
          {:else}
            {m.codeReview_tabContent_stageChanges_description()}
          {/if}
        </p>
        {#if hasChanges}
          <Button variant="default" size="sm" onclick={handleTriggerReview}>
            <Fa icon={faWandMagicSparkles} class="h-4 w-4 mr-2" />
            {m.codeReview_tabContent_startReview_label()}
          </Button>
        {/if}
      </div>
    {:else if isRunning}
      <!-- Running state -->
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-2">
            <Fa icon={faSpinner} class="h-4 w-4 animate-spin text-primary" />
            <span class="text-sm font-medium">{m.codeReview_tabContent_reviewing_label()}</span>
          </div>
          <Button variant="ghost" size="xs" onclick={handleStop}>
            <Fa icon={faStop} class="h-3 w-3 mr-1" />
            {m.codeReview_tabContent_stop_label()}
          </Button>
        </div>
        {#if streamingText}
          <div class="text-sm text-subtle">
            <MarkdownViewer content={streamingText} isStreaming />
          </div>
        {:else}
          <div class="space-y-3">
            <Skeleton class="h-4 w-full" />
            <Skeleton class="h-4 w-3/4" />
            <Skeleton class="h-4 w-1/2" />
          </div>
        {/if}
      </div>
    {:else if isComplete || walkthrough || walkthroughStatus !== 'idle'}
      <!-- Completed state with walkthrough -->
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-2">
            <Badge
              variant="default"
              class="text-xs gap-1 bg-green-500/10 text-green-600 border-green-500/20"
            >
              <Fa icon={faCheck} class="h-3 w-3" />
              {m.codeReview_tabContent_reviewComplete_label()}
            </Badge>
          </div>
          <Button variant="ghost" size="xs" onclick={handleTriggerReview}>
            <Fa icon={faRotateRight} class="h-3 w-3 mr-1" />
            {m.codeReview_tabContent_rereview_label()}
          </Button>
        </div>

        <!-- Walkthrough section -->
        <CodeWalkthroughSection
          {walkthrough}
          {workspacePath}
          changes={$ftStagedChanges$}
          status={walkthroughStatus}
          error={walkthroughError}
          onRegenerate={handleGenerateWalkthrough}
        />
      </div>
    {:else if error}
      <!-- Error state -->
      <div class="flex flex-col items-center justify-center py-8 text-center">
        <p class="text-sm text-red-500 mb-4">{error}</p>
        <Button variant="outline" size="sm" onclick={handleTriggerReview}>
          <Fa icon={faRotateRight} class="h-4 w-4 mr-2" />
          {m.codeReview_tabContent_tryAgain_label()}
        </Button>
      </div>
    {/if}
  </div>
</div>
