#!/usr/bin/env tsx
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { format } from 'prettier';
import { canonicalPatternManifest } from '../src/lib/components/patterns/manifest';
import { buttonMetadata } from '../src/lib/components/ui/button/button.meta';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const cheatsheetPath = path.resolve(
  projectRoot,
  '../../docs/fe/DESIGN_SYSTEM_CHEATSHEET.md',
);

function bullets(values: readonly string[], fallback = 'None recorded.'): string {
  return values.length ? values.map((value) => `- ${value}`).join('\n') : `- ${fallback}`;
}

export async function generateDesignCheatsheet(): Promise<string> {
  const buttonGuidance = buttonMetadata.apiGuidance;
  if (!buttonGuidance) throw new Error('Button metadata must publish API guidance.');
  const buttonEmphasis = buttonGuidance.emphasis
    .map(
      ({ value, label, guidance }, index) =>
        `${index + 1}. **${label}:** \`${value}\` — ${guidance}`,
    )
    .join('\n');
  const buttonSizes = buttonGuidance.sizes
    .map(
      ({ value, iconValue, label }) => `- **${label}:** \`${value}\`; icon-only \`${iconValue}\`.`,
    )
    .join('\n');
  const buttonAliases = buttonGuidance.compatibilityAliases
    .map(
      ({ prop, alias, replacement }) => `- \`${prop}="${alias}"\` → \`${prop}="${replacement}"\``,
    )
    .join('\n');
  const sections = canonicalPatternManifest.map(
    (pattern) => `## ${pattern.id}

- **Import:** \`${pattern.publicImport}\`
- **Public API / props surface:** ${pattern.exports.map((name) => `\`${name}\``).join(', ')}
- **Catalog:** [\`/sandbox/${pattern.id}\`](../../packages/cloudlands-fe/src/routes/sandbox/[slug]/+page.svelte)

### Use when

${bullets(pattern.useWhen)}

### Do not use when

${bullets(pattern.dontUseWhen)}

### Replaces

${bullets(pattern.replaces)}
`,
  );

  const markdown = `<!-- Generated by packages/cloudlands-fe/scripts/generate-design-cheatsheet.ts. Do not edit. -->
# Design System Cheatsheet

Pattern-first routing for product UI. Open the catalog URL in \`pnpm run dev:ui\` to inspect live fixtures.

## Color roles

- **Primary action fill:** \`bg-primary\` with \`text-primary-foreground\`.
- **Primary ink:** \`text-primary-ink\`, \`border-primary-ink\`, or \`ring-primary-ink\` for primary-colored text and outlines on neutral surfaces.
- **Focus:** the global 1px \`--focus-ring\` outline is the keyboard-focus baseline; legacy \`ring-ring\` utilities remain compatible during migration.

## Surfaces and interaction

- **Import:** \`SurfaceProvider\`, \`surfaceClasses\`, and \`surfaceHoverClasses\` from \`$lib/components/ui\`.
- **Ladder:** \`bg-surface-1\` through \`bg-surface-8\` pair with \`shadow-surface-1\` through \`shadow-surface-8\`.
- **Overlays:** render at two levels above their substrate, capped at level 8, and provide that level to nested content.
- **Overlay recipe:** \`.overlay-surface\` uses the 8px medium radius and two-layer \`--elevation-overlay\`; its boundary is 0px in light themes and a 1px semantic border in dark themes.
- **States:** use \`bg-hover\`, \`bg-active\`, \`bg-selected\`, and \`bg-danger-background\` rather than physical colors.

## Motion

- **Import:** \`$lib/motion\`
- **Tiers:** \`fast\`, \`moderate\`, and \`slow\`; intros use the spring timing and outros use its paired crisp timing.
- **Transitions:** \`fade\`, \`fly\`, \`slide\`, \`scale\`, \`blur\`, and \`draw\` accept only \`tier\` plus semantic \`distance\` / \`axis\` options.
- **Continuous values:** \`Spring\`, \`springValue\`, and \`tweenedValue\` bind updates to a tier.
- **Reduced motion:** all helpers settle instantly. Never pass a duration, easing, or delay.

## Loading indicator

- **Import:** \`IntentMarkLoader\` from \`$lib/components/ui/indicators\`
- **Use:** IntentMarkLoader is the only indeterminate indicator. It inherits \`currentColor\`; use bloom by default, and pulse or twist only for an explicit status-derived variant. Use the Screen pattern's \`LoadingState\` for structured loading shells.

## Raw markup

- **Zero rule:** Production code outside approved primitive implementations contains zero raw \`button\`, \`input\`, \`select\`, or \`textarea\` controls. Use the public design-system primitive instead; there are no file exceptions.
- **Approved-root criterion:** A file may host a raw control only when that file is itself the control primitive: it renders the native element and owns its recipe and focus contract. A file that merely uses a control is not an approved root.

## Button

- **Import:** \`${buttonMetadata.publicImport}\`
- **Rule:** Choose the lowest emphasis that still communicates the action. Use one primary action per region.

### Preferred emphasis ladder

${buttonEmphasis}

### Preferred size ladder

${buttonSizes}

### Compatibility aliases

Existing callers may retain these names, but new code must use the canonical replacement:

${buttonAliases}

- **Geometry escape hatch:** use \`wrapContent={false}\` only for full-card interactive containers whose flex or grid layout requires slotted regions to remain direct button children.

### Primitive-internal button decisions

- \`sidebar/sidebar-rail.svelte\` retains its native button because the rail is the control primitive: it owns resize, peek, toggle, pointer, and focus behavior.
- \`sidebar/sidebar-menu-button.svelte\` retains its native button because it is the menu-button control primitive and owns the row recipe, roving focus, active state, and tooltip trigger contract.
- \`sidebar/sidebar-menu-action.svelte\` uses \`Button\`; it is an action inside the sidebar row primitive rather than the control primitive itself.
- \`sidebar/sidebar-group-action.svelte\` uses \`Button\`; it is an action inside the sidebar group primitive rather than the control primitive itself.
- \`toast/ToastCloseButton.svelte\` uses \`Button\`; it is an inset 40px ghost close action layered on the shared focus contract.
- \`tooltip/TooltipRich.svelte\` uses \`Button\` for its optional close action; the tooltip owns content and positioning, not a distinct button contract.
- \`badge/badge.svelte\` uses \`Button\` for its remove action; the badge owns status presentation, not a distinct button contract.

## Button, Tabs, Toggle, and Badge recipes

- **Borders:** Filled and ghost Buttons, resting Tabs, default Toggles, Toggle Groups, and Badge bodies are borderless. Use the Button \`outline\` variant or another explicit outline/input recipe when a 1px boundary is required.
- **Segmented Tabs:** Use a 36px rail and selected pill, an 8px radius, 12px horizontal trigger padding, and a 6px icon gap.
- **Labels:** Resting control and Badge labels use regular weight; selected Tabs and Toggles use medium weight.
- **Badge:** Badge bodies use an 8px radius. Removable badges retain a 16px circular end slot for the close control.
- **Focus:** Preserve the shared 1px solid outline, non-zero offset, and no-shadow focus tuple on every interactive control.

## Option and list rows

- **Recipe:** Menu, Select, Combobox, Radio Group, and Sidebar share a 36px default row, 8px item radius, 8px horizontal item padding, and a 4px container inset.
- **States:** option labels are 13px / 400 at rest and 500 when selected; hover and selected layers use the measured inset item bounds.
- **End slot:** checks, indicators, and chevrons use one aligned 16px end slot inside the item padding.
- **Popups:** option popups use semantic surface backgrounds with the overlay elevation; preserve viewport collision handling, scrolling, and focus restoration.
- **Focus:** keep the 1px solid outline, non-zero offset, and no-shadow focus tuple. Do not reduce disabled or muted contrast.

${sections.join('\n')}\n`;
  return format(markdown, { parser: 'markdown' });
}

export async function runDesignCheatsheetGenerator(
  mode: 'write' | 'check',
  target = cheatsheetPath,
): Promise<{ exitCode: number; message: string }> {
  const generated = await generateDesignCheatsheet();
  if (mode === 'check') {
    const committed = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
    return committed === generated
      ? { exitCode: 0, message: 'Design-system cheatsheet is current.' }
      : {
          exitCode: 1,
          message:
            'Design-system cheatsheet is stale. Run `pnpm exec tsx scripts/generate-design-cheatsheet.ts`.',
        };
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, generated);
  return { exitCode: 0, message: `Wrote ${path.relative(projectRoot, target)}.` };
}

function invokedAsCli(): boolean {
  return (
    Boolean(process.argv[1]) && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
  );
}

if (invokedAsCli()) {
  const mode = process.argv.includes('--check') ? 'check' : 'write';
  const result = await runDesignCheatsheetGenerator(mode);
  console[`${result.exitCode === 0 ? 'log' : 'error'}`](result.message);
  process.exitCode = result.exitCode;
}
