#!/usr/bin/env tsx
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import { canonicalPatternManifest } from '../src/lib/components/patterns/manifest';
import { buttonMetadata } from '../src/lib/components/ui/button/button.meta';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const cheatsheetPath = path.resolve(projectRoot, 'docs/DESIGN_SYSTEM_CHEATSHEET.md');
const regenerateCommand = 'pnpm exec tsx scripts/generate-design-cheatsheet.ts';

function bullets(values: readonly string[], fallback = 'None recorded.'): string {
  return values.length ? values.map((value) => `- ${value}`).join('\n') : `- ${fallback}`;
}

export async function generateDesignCheatsheet(): Promise<string> {
  const buttonGuidance = buttonMetadata.apiGuidance;
  if (!buttonGuidance) throw new Error('Button metadata must publish API guidance.');
  const buttonEmphasis = buttonGuidance.emphasis
    .map(
      ({ value, label, guidance }, index) =>
        `${index + 1}. **${label}:** \`${value}\` — ${guidance}`,
    )
    .join('\n');
  const buttonSizes = buttonGuidance.sizes
    .map(
      ({ value, iconValue, label }) => `- **${label}:** \`${value}\`; icon-only \`${iconValue}\`.`,
    )
    .join('\n');
  const buttonAliases = buttonGuidance.compatibilityAliases
    .map(
      ({ prop, alias, replacement }) => `- \`${prop}="${alias}"\` → \`${prop}="${replacement}"\``,
    )
    .join('\n');
  const sections = canonicalPatternManifest.map(
    (pattern) => `## ${pattern.id}

- **Import:** \`${pattern.publicImport}\`
- **Public API / props surface:** ${pattern.exports.map((name) => `\`${name}\``).join(', ')}
- **Catalog:** [\`/sandbox/${pattern.id}\`](../src/routes/sandbox/[slug]/+page.svelte)

### Use when

${bullets(pattern.useWhen)}

### Do not use when

${bullets(pattern.dontUseWhen)}

### Replaces

${bullets(pattern.replaces)}
`,
  );

  const markdown = `<!-- Generated by scripts/generate-design-cheatsheet.ts. Do not edit. -->
# Design System Cheatsheet

Pattern-first routing for product UI. Open the catalog URL in \`pnpm run dev:ui\` to inspect live fixtures.

## Color roles

- **Primary action fill:** \`bg-primary\` with \`text-primary-foreground\`.
- **Primary ink:** \`text-primary-ink\`, \`border-primary-ink\`, or \`ring-primary-ink\` for primary-colored text and outlines on neutral surfaces.
- **Focus:** the global 1px \`--focus-ring\` outline is the keyboard-focus baseline; legacy \`ring-ring\` utilities remain compatible during migration.

## Surfaces and interaction

- **Canvas:** use \`bg-background\` for the page and ordinary content; group controls with spacing first.
- **Contained section:** use \`bg-card\` when a distinct group needs one enclosing boundary, such as a panel or card.
- **Floating overlay:** use \`bg-popover\` for temporary content above the page, such as a menu, popover or tooltip.
- Use one enclosing boundary per group; avoid wrapping an already contained section in another border or shadow.
- **Compatibility helpers:** \`SurfaceProvider\`, \`surfaceClasses\`, and \`surfaceHoverClasses\` from \`$lib/components/ui\`.
- **Internal levels (compatibility, not additional composition choices):** \`bg-surface-1\` through \`bg-surface-8\` pair with \`shadow-surface-1\` through \`shadow-surface-8\`.
- **Overlays:** render at two levels above their substrate, capped at level 8, and provide that level to nested content.
- **Overlay recipe:** \`.overlay-surface\` uses the 8px medium radius and two-layer \`--elevation-overlay\`; its boundary is 0px in light themes and a 1px semantic border in dark themes.
- **States:** use \`bg-hover\`, \`bg-active\`, \`bg-selected\`, and \`bg-danger-background\` rather than physical colors.

## Menus and choices

- **Commands:** \`ActionMenu\` and \`defineActions\` from \`$lib/components/patterns/action-menu\`; use one readonly action model for overflow and right-click. Only the trigger/\`contextMenu\` anchor differs.
- **Kinds:** \`action\`, \`checkbox\`, \`radio-group\` with \`radio\` children, \`submenu\`, \`section\`, and passive \`label\`. Use \`when\` for visibility, \`disabledReason\` for an unavailable command's explanation, and \`closeOnSelect\` to override the command-close / choice-stay-open default. Labels render as \`Menu.Label\`, never inline ActionBar buttons; sidebar adapters accept \`{ type: 'label', label, id? }\`.
- **Composition:** \`Menu.Content\`, \`Menu.Item\`, \`Menu.CheckboxItem\`, \`Menu.RadioItem\`, and \`Menu.Sub\` from \`$lib/components/ui/menu\`. Do not make decorative checkmarks stand in for checked semantics.
- **Indicators:** \`Menu.Indicator\` owns glyph, trailing slot, and \`aria-hidden\`; set \`state="checked" | "mixed" | "submenu" | "empty"\`. Render empty to reserve spacing; the row still owns \`aria-checked\` or \`aria-selected\`.
- **Adapter recipes:** public \`menuOverlay()\` and \`menuItem()\` from \`$lib/components/ui/menu\` supply canonical shell/row styling, not interaction behavior. Feature code should prefer semantic Menu components.
- **Unavailable commands:** \`Menu.CommandItem disabledReason\` accepts localized explanatory text, disables activation, and appends its reason to \`aria-describedby\`; preserve the command rather than silently hiding it when its unavailability needs explanation.
- **Context invocation:** \`getSidebarContextPosition(event)\` from \`$lib/components/ui/sidebar-context-menu/types\` supports pointer and Shift+F10/context-menu-key invocation. Preserve \`returnFocus\`; existing context/overflow adapters share the action renderer.
- **Values:** use Select for a closed value set; \`Combobox\` from \`$lib/components/ui/combobox\` for search, remote options, groups, and multiple selection. Supply a purpose-specific \`ariaLabel\`; use \`ariaLabelledby\` / \`ariaDescribedby\` for associated fields.
- **Async choices:** \`onsearch\` accepts sync or async results; \`errorText\`, \`retryText\`, and \`onsearcherror\` distinguish failure from empty results. Keep status/retry outside options and retain selected identity when results change.
- **Choice acceptance:** \`onchange\` is change-only; \`oncommit(value, option)\` also reports explicit same-value acceptance without clearing a single selection. Use one acceptance handler to avoid duplicate domain actions.
- **Embedded choices:** \`staticPosition\` is layout-only. Bind \`inputRef\` for host autofocus; coordinate \`onopenchange(false)\` or the shared Escape layer with the host for one-step dismissal and focus return.
- **Enforcement:** \`intent/no-raw-menu-surface\` and \`intent/no-raw-menu-row\` verify canonical shell/row bindings and semantics. Legacy callers only shrink; new code uses public canonical subpaths.
- **Boundaries:** rich forms use Popover/dialog; native Electron menus and the hardware radial selector retain their documented native/spatial contracts. See [menu guidance](DESIGN_SYSTEM.md#compact-command-menus).

## Typography

- **Roles:** \`type-caption\` for compact controls, navigation and short metadata; \`type-body\` for messages, documents, explanatory copy and expanded form content; \`type-title\` / \`type-display\` for section / page headings. Use \`SettingsFieldRow\` for label-and-control rows.
- **Emphasis:** Use medium weight on the same role instead of inventing another size. Label, body-strong and display-large are compatibility aliases, not additional styles.
- **Style:** Use sentence case; avoid uppercase section labels, tracking changes, and bold as decoration. Do not change typography on hover by default; reserve motion for state and spatial relationships.
- **Zero rule:** Never use raw \`text-xs\`, \`text-sm\`, \`text-base\` or \`text-lg\` in settings components, routes or patterns. Pair \`font-medium!\` with a \`type-*\` role on the same element; \`intent/no-raw-typography\` enforces this.

| Use | Value (size / line height) | Weight |
| --- | --- | --- |
| Compact controls, navigation, short metadata (\`type-caption\`) | 13px / 18px | 400; 500 for selection or label emphasis |
| Messages, documents, explanatory copy, expanded form content (\`type-body\`) | 15px / 22px | 400; 500 for emphasis |
| Section title (\`type-title\`) | 17px / 24px | 500 |
| Page title (\`type-display\`) | 22px / 28px | 500 |
| Code (\`type-code\`) | 13px / 20px | 400; monospace only where content is code |

Badge is a narrow microtext exception: \`badge.variants.ts\` retains \`text-[12px]\` for default
and \`text-[11px]\` for compact badges, both medium weight, to preserve the existing dense status
chip proportions. These are not new general typography roles; do not copy them into controls or
navigation. \`scripts/design-token-allowlist.json\` caps this file at those two arbitrary utilities.

## Motion

- **Import:** \`$lib/motion\`
- **Tiers:** \`fast\`, \`moderate\`, and \`slow\`; bounded easing only, never overshoot or bounce. Outros use the paired crisp timing.
- **Transitions:** \`fade\`, \`fly\`, \`slide\`, \`scale\`, \`blur\`, and \`draw\` accept only \`tier\` plus semantic \`distance\` / \`axis\` options.
- **Continuous values:** \`Spring\`, \`springValue\`, and \`tweenedValue\` use bounded ease-out, preserving current position (not momentum) on interruption. Spring names are compatibility aliases.
- **Moving focus:** use the \`moderate\` tier for hover/focus backgrounds and selection geometry. Keep one persistent highlight between rows; a new session is only for list re-entry.
- **Reduced motion:** all helpers settle instantly. Never pass a duration, easing, or delay.

## Loading indicator

- **Import:** \`IntentMarkLoader\` from \`$lib/components/ui/indicators\`
- **Use:** IntentMarkLoader is the only indeterminate indicator. It inherits \`currentColor\`; use bloom by default, and pulse or twist only for an explicit status-derived variant. Use the Screen pattern's \`LoadingState\` for structured loading shells.

## Raw markup

- **Zero rule:** Production code outside approved primitive implementations contains zero raw \`button\`, \`input\`, \`select\`, or \`textarea\` controls. Use the public design-system primitive instead; there are no file exceptions.
- **Approved-root criterion:** A file may host a raw control only when that file is itself the control primitive: it renders the native element and owns its recipe and focus contract. A file that merely uses a control is not an approved root.

## Button

- **Import:** \`${buttonMetadata.publicImport}\`
- **Rule:** Choose the lowest emphasis that still communicates the action. Use one primary action per region.

### Preferred emphasis ladder

${buttonEmphasis}

### Preferred size ladder

${buttonSizes}

### Compatibility aliases

Existing callers may retain these names, but new code must use the canonical replacement:

${buttonAliases}

- **Geometry escape hatch:** use \`wrapContent={false}\` only for full-card interactive containers whose flex or grid layout requires slotted regions to remain direct button children.

### Primitive-internal button decisions

- \`sidebar/sidebar-rail.svelte\` retains its native button because the rail is the control primitive: it owns resize, peek, toggle, pointer, and focus behavior.
- \`sidebar/sidebar-menu-button.svelte\` retains its native button because it is the menu-button control primitive and owns the row recipe, roving focus, active state, and tooltip trigger contract.
- \`sidebar/sidebar-menu-action.svelte\` uses \`Button\`; it is an action inside the sidebar row primitive rather than the control primitive itself.
- \`sidebar/sidebar-group-action.svelte\` uses \`Button\`; it is an action inside the sidebar group primitive rather than the control primitive itself.
- \`toast/ToastCloseButton.svelte\` uses \`Button\`; it is an inset 40px ghost close action layered on the shared focus contract.
- \`tooltip/TooltipRich.svelte\` uses \`Button\` for its optional close action; the tooltip owns content and positioning, not a distinct button contract.
- \`badge/badge.svelte\` uses \`Button\` for its remove action; the badge owns status presentation, not a distinct button contract.

## Badge status guidance

Use a Badge for a short status attached to an item. Name the state in text; colour
reinforces meaning and must never be the only cue. Use either \`variant="solid"\`
or \`variant="dot"\` with the same mapping:

| Meaning | Colour prop | Example |
| --- | --- | --- |
| Neutral | \`gray\` | Draft |
| Information | \`blue\` | In progress |
| Success | \`green\` | Complete |
| Warning | \`amber\` | Needs attention |
| Danger | \`red\` | Failed |

Use plain text for ordinary metadata, Button for a primary action, InputMessage
for field validation, and an alert when the message needs an explanation.
A Badge should not turn every piece of metadata into a competing visual marker.

### Categorical colours

The 17 named colours are for categorisation only, such as distinguishing named
project labels. Keep the category visible in text and its colour assignment
consistent. Do not use this palette to invent more status meanings.

### Compatibility

Legacy \`default\`, \`secondary\`, \`outline\`, \`destructive\`, \`success\`, and \`info\`
variants remain supported for existing callers. New code uses \`solid\` or \`dot\`
with an explicit colour from the status mapping above.

## Button, Tabs, Toggle, and Badge recipes

- **Borders:** Filled and ghost Buttons, resting Tabs, default Toggles, Toggle Groups, and Badge bodies are borderless. Use the Button \`outline\` variant or another explicit outline/input recipe when a 1px boundary is required.
- **Segmented Tabs:** Use a 36px rail and selected pill, an 8px radius, 12px horizontal trigger padding, and a 6px icon gap.
- **Labels:** Resting control and Badge labels use regular weight; selected Tabs and Toggles use medium weight.
- **Badge:** Badge bodies use an 8px radius. Removable badges retain a 16px circular end slot for the close control.
- **Focus:** Preserve the shared 1px solid outline, non-zero offset, and no-shadow focus tuple on every interactive control.

## Option and list rows

- **Families:** Navigation rows use 28/32px compact/regular heights; content rows grow with their content (\`ListRow\` retains 36/48px minimums); setting rows use label/control/description tiers. See [Option and list rows](DESIGN_SYSTEM.md#option-and-list-rows) for the height and alignment table.
- **Alignment:** Center icons and avatars on the first text line, never on the full multiline block. ListRow and Menu.ActionRow provide this by default; custom rows use a top-aligned layout and an icon slot of one line-height with matching typography. Place secondary copy below. Use \`type-caption\` for compact row labels and metadata, and \`type-body\` for expanded form content.
- **States:** option labels are 13px / 400 at rest and 500 when selected; hover and selected layers use the measured inset item bounds.
- **End slot:** checks, indicators, and chevrons use one aligned 16px end slot inside the item padding.
- **Popups:** option popups use semantic surface backgrounds with the overlay elevation; preserve viewport collision handling, scrolling, and focus restoration.
- **Focus:** keep the 1px solid outline, non-zero offset, and no-shadow focus tuple. Do not reduce disabled or muted contrast.

${sections.join('\n')}\n`;
  const projectConfig = await resolveConfig(cheatsheetPath);
  return format(markdown, { ...projectConfig, parser: 'markdown' });
}

export async function runDesignCheatsheetGenerator(
  mode: 'write' | 'check',
  target = cheatsheetPath,
): Promise<{ exitCode: number; message: string }> {
  const generated = await generateDesignCheatsheet();
  const displayPath = path.relative(projectRoot, target);
  if (mode === 'check') {
    if (!fs.existsSync(target)) {
      return {
        exitCode: 1,
        message: `${displayPath} is missing. Run \`${regenerateCommand}\`.`,
      };
    }
    return fs.readFileSync(target, 'utf8') === generated
      ? { exitCode: 0, message: `${displayPath} is current.` }
      : {
          exitCode: 1,
          message: `${displayPath} is stale. Run \`${regenerateCommand}\`.`,
        };
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, generated);
  return { exitCode: 0, message: `Wrote ${displayPath}.` };
}

function invokedAsCli(): boolean {
  return (
    Boolean(process.argv[1]) && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
  );
}

if (invokedAsCli()) {
  const mode = process.argv.includes('--check') ? 'check' : 'write';
  const result = await runDesignCheatsheetGenerator(mode);
  console[`${result.exitCode === 0 ? 'log' : 'error'}`](result.message);
  process.exitCode = result.exitCode;
}
