export const uiComponentGuardrails = {
  internalImports: {
    '$lib/components/ui/button/button.svelte': 25,
    '$lib/components/ui/button/index.js': 1,
    '$lib/components/ui/checkbox/checkbox.svelte': 2,
    '$lib/components/ui/indicators/AgentBadge.svelte': 1,
    '$lib/components/ui/indicators/UnsavedIndicator.svelte': 1,
    '$lib/components/ui/input/index.js': 1,
    '$lib/components/ui/input/input.svelte': 6,
    '$lib/components/ui/label/label.svelte': 1,
    '$lib/components/ui/separator/index.js': 1,
    '$lib/components/ui/sheet/index.js': 1,
    '$lib/components/ui/skeleton/index.js': 1,
    '$lib/components/ui/skeleton/skeleton.svelte': 2,
    '$lib/components/ui/switch/switch.svelte': 2,
    '$lib/components/ui/textarea/textarea.svelte': 1,
    '$lib/components/ui/toast/Toast.svelte': 1,
    '$lib/components/ui/tooltip/LinkTooltip.svelte': 1,
    '$lib/components/ui/tooltip/Tooltip.svelte': 5,
    '$lib/components/ui/tooltip/TooltipRich.svelte': 1,
    '$lib/components/ui/tooltip/github-link-card.preview.svelte': 1,
    '$lib/components/ui/tooltip/index.js': 2,
    '$lib/components/ui/tooltip/link-tooltip-state.svelte': 1,
    'relative:src/lib/components/ui/CollapsiblePanel.svelte': 1,
    'relative:src/lib/components/ui/Header.svelte': 2,
    'relative:src/lib/components/ui/MediaLightbox.svelte': 1,
    'relative:src/lib/components/ui/Portal.svelte': 3,
    'relative:src/lib/components/ui/VSCodePanel.svelte': 1,
    'relative:src/lib/components/ui/VSCodeScrollablePanel.svelte': 2,
    'relative:src/lib/components/ui/button/button.svelte': 9,
    'relative:src/lib/components/ui/button/index.ts': 1,
    'relative:src/lib/components/ui/checkbox/checkbox.svelte': 1,
    'relative:src/lib/components/ui/combobox/index.ts': 3,
    'relative:src/lib/components/ui/dropdown-menu.svelte': 1,
    'relative:src/lib/components/ui/dialog/overlay-motion.svelte.ts': 2,
    'relative:src/lib/components/ui/dialog/overlay-root.svelte': 1,
    'relative:src/lib/components/ui/highlight/highlight-target.ts': 1,
    'relative:src/lib/components/ui/input/input.svelte': 1,
    'relative:src/lib/components/ui/list/index.ts': 1,
    'relative:src/lib/components/ui/menu/index.ts': 1,
    'relative:src/lib/components/ui/menu/menu-list-highlight.svelte': 3,
    'relative:src/lib/components/ui/menu/menu-recipes.ts': 5,
    'relative:src/lib/components/ui/scroll-area/index.ts': 2,
    'relative:src/lib/components/ui/skeleton/index.ts': 2,
    'relative:src/lib/components/ui/surface-context.ts': 1,
    'relative:src/lib/components/ui/tooltip/Tooltip.svelte': 2,
  },
  patternAdoption: {
    formDialog: 10,
    listView: 31,
    screen: 9,
    settingsForm: 1,
  },
  rawControls: { button: 0, input: 0, select: 0, textarea: 0 },
} as const;
