// @vitest-environment node
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { build, createServer } from 'vite';
import { compactParaglideDevPlugin } from './vite-plugin-paraglide-dev.mjs';

const cleanups = [];
afterEach(async () => {
  while (cleanups.length) await cleanups.pop()();
});

const documentation = `/** ${'Generated message documentation. '.repeat(2000)} */`;
const message = `${documentation}
export function greeting(name, locale = 'en') {
  return (locale === 'fr' ? 'Bonjour ' : 'Hello ') + name;
}`;
const loadModule = (code) =>
  import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);

describe('generated Paraglide dev payload', () => {
  it('preserves message arguments and locale selection while reducing generated bytes', async () => {
    const plugin = compactParaglideDevPlugin('/project/src/shared/paraglide');
    const result = await plugin.transform(message, '/project/src/shared/paraglide/messages/en.js');
    const module = await loadModule(result.code);
    expect(module.greeting('Ada')).toBe('Hello Ada');
    expect(module.greeting('René', 'fr')).toBe('Bonjour René');
    expect(Buffer.byteLength(result.code)).toBeLessThan(500);
  });

  it('leaves authored files, adjacent directories, and non-JS resources untouched', async () => {
    const plugin = compactParaglideDevPlugin('/project/src/shared/paraglide/');
    for (const file of [
      '/project/src/shared/greeting.js',
      '/project/src/shared/paraglide-backup/messages.js',
      '/project/src/shared/paraglide/messages.json',
    ]) {
      expect(await plugin.transform(message, file)).toBeNull();
    }
  });

  it('supports Windows paths and Vite query suffixes', async () => {
    const plugin = compactParaglideDevPlugin('C:/project/src/shared/paraglide');
    const result = await plugin.transform(
      message,
      'C:\\project\\src\\shared\\paraglide\\messages.js?t=123',
    );
    expect((await loadModule(result.code)).greeting('Ada')).toBe('Hello Ada');
  });

  it('serves compact modules, preserves authored maps, and re-transforms invalidated translations', async () => {
    const root = await mkdtemp(path.join(tmpdir(), 'paraglide-dev-'));
    cleanups.push(() => rm(root, { recursive: true, force: true }));
    const generatedRoot = path.join(root, 'generated');
    await mkdir(generatedRoot);
    const generatedFile = path.join(generatedRoot, 'message.js');
    await writeFile(generatedFile, message);
    await writeFile(path.join(root, 'authored.ts'), 'export const value: number = 42;');
    const server = await createServer({
      configFile: false,
      root,
      logLevel: 'silent',
      plugins: [compactParaglideDevPlugin(generatedRoot)],
      server: { host: '127.0.0.1', port: 0, watch: null },
      optimizeDeps: { noDiscovery: true, include: [] },
    });
    cleanups.push(() => server.close());
    await server.listen();
    const origin = server.resolvedUrls.local[0];
    const response = await fetch(`${origin}generated/message.js`);
    expect(response.status).toBe(200);
    const served = await response.text();
    expect(Buffer.byteLength(served)).toBeLessThan(500);
    expect((await loadModule(served)).greeting('Ada', 'fr')).toBe('Bonjour Ada');
    expect(await readFile(generatedFile, 'utf8')).toBe(message);

    const authored = await server.transformRequest('/authored.ts');
    expect(authored.map.sourcesContent).toContain('export const value: number = 42;');

    await writeFile(
      path.join(generatedRoot, 'runtime.js'),
      "export let locale = 'en'; export const setLocale = (next) => { locale = next; };",
    );
    await writeFile(
      path.join(generatedRoot, 'current.js'),
      `import { locale } from './runtime.js';
      import { greeting } from './message.js';
      export const currentGreeting = (name) => greeting(name, locale);`,
    );
    const runtime = await server.ssrLoadModule('/generated/runtime.js');
    const current = await server.ssrLoadModule('/generated/current.js');
    expect(current.currentGreeting('Ada')).toBe('Hello Ada');
    runtime.setLocale('fr');
    expect(current.currentGreeting('Ada')).toBe('Bonjour Ada');

    await writeFile(generatedFile, message.replace('Bonjour ', 'Salut '));
    server.moduleGraph.onFileChange(generatedFile);
    const edited = await (await fetch(`${origin}generated/message.js`)).text();
    expect((await loadModule(edited)).greeting('Ada', 'fr')).toBe('Salut Ada');
  });

  it('preserves original generated sources in production build maps', async () => {
    const root = await mkdtemp(path.join(tmpdir(), 'paraglide-build-'));
    cleanups.push(() => rm(root, { recursive: true, force: true }));
    const entry = path.join(root, 'message.js');
    await writeFile(entry, message);
    const bundle = await build({
      configFile: false,
      root,
      logLevel: 'silent',
      plugins: [compactParaglideDevPlugin(root)],
      build: {
        write: false,
        minify: false,
        sourcemap: true,
        lib: { entry, formats: ['es'] },
      },
    });
    const chunk = bundle[0].output.find((output) => output.type === 'chunk');
    expect(chunk.map.sourcesContent).toContain(message);
    expect((await loadModule(chunk.code)).greeting('Ada', 'fr')).toBe('Bonjour Ada');
  });
});
