/**
 * Copy/text constants for WorkspaceProgressCard
 *
 * This file is auto-generated by the sandbox at /sandbox-progress-card
 * Edit values here or use the sandbox UI to modify them.
 */

import { m } from '$shared/paraglide/messages.js';

export const progressCardCopy = {
  loading: {
    get headline() {
      return m.workspace_progressCopy_loading_headline();
    },
    subtext: '',
  },
  specCreating: {
    get headline() {
      return m.workspace_progressCopy_specCreating_headline();
    },
    subtext: '',
  },
  specReady: {
    get headline() {
      return m.workspace_progressCopy_specReady_headline();
    },
    get subtext() {
      return m.workspace_progressCopy_specReady_subtext();
    },
  },
  tasksReady: {
    get headline() {
      return m.workspace_progressCopy_tasksReady_headline();
    },
    get subtext() {
      return m.workspace_progressCopy_tasksReady_subtext();
    },
  },
  tasksInProgress: {
    early: {
      get headline() {
        return m.workspace_progressCopy_tasksEarly_headline();
      },
      // subtext uses template: workspace_progressCopy key with completed/total params
    },
    mid: {
      get headline() {
        return m.workspace_progressCopy_tasksMid_headline();
      },
      // subtext uses template: workspace_progressCopy key with percent param
    },
    late: {
      get headline() {
        return m.workspace_progressCopy_tasksLate_headline();
      },
      // subtext uses template: workspace_progressCopy key with remaining param
    },
  },
  changesUnstaged: {
    // headline uses template: workspace_progressCopy key with count param
    get subtext() {
      return m.workspace_progressCopy_changesUnstaged_subtext();
    },
    get actionLabel() {
      return m.workspace_progressCopy_changesUnstaged_actionLabel();
    },
    get actionTooltip() {
      return m.workspace_progressCopy_changesUnstaged_actionTooltip();
    },
  },
  changesStaged: {
    // headline uses template: workspace_progressCopy key with count param
    get subtext() {
      return m.workspace_progressCopy_changesStaged_subtext();
    },
    get actionLabel() {
      return m.workspace_progressCopy_changesStaged_actionLabel();
    },
    get actionTooltip() {
      return m.workspace_progressCopy_changesStaged_actionTooltip();
    },
  },
  commitsUnpushed: {
    // headline uses template: workspace_progressCopy key with count param
    get subtextNew() {
      return m.workspace_progressCopy_commitsUnpushed_subtextNew();
    },
    get subtextExisting() {
      return m.workspace_progressCopy_commitsUnpushed_subtextExisting();
    },
    get actionLabelNew() {
      return m.workspace_progressCopy_commitsUnpushed_actionLabelNew();
    },
    get actionLabelExisting() {
      return m.workspace_progressCopy_commitsUnpushed_actionLabelExisting();
    },
    get actionTooltip() {
      return m.workspace_progressCopy_commitsUnpushed_actionTooltip();
    },
  },
  prOpen: {
    // headline uses template: workspace_progressCopy key with number param
    get subtext() {
      return m.workspace_progressCopy_prOpen_subtext();
    },
    get actionLabel() {
      return m.workspace_progressCopy_prOpen_actionLabel();
    },
    get actionTooltip() {
      return m.workspace_progressCopy_prOpen_actionTooltip();
    },
  },
  prApproved: {
    // headline uses template: workspace_progressCopy key with number param
    get subtext() {
      return m.workspace_progressCopy_prApproved_subtext();
    },
    get actionLabel() {
      return m.workspace_progressCopy_prApproved_actionLabel();
    },
    get actionTooltip() {
      return m.workspace_progressCopy_prApproved_actionTooltip();
    },
  },
  allDone: {
    get headline() {
      return m.workspace_progressCopy_allDone_headline();
    },
    subtext: '',
  },
} as const;

export type ProgressCardCopy = typeof progressCardCopy;
