/**
 * Copy/text constants for WorkspaceProgressCard
 *
 * This file is auto-generated by the sandbox at /sandbox-progress-card
 * Edit values here or use the sandbox UI to modify them.
 */

export const progressCardCopy = {
  loading: {
    headline: 'Loading...',
    subtext: '',
  },
  specCreating: {
    headline: 'Coordinator writing spec...',
    subtext: '',
  },
  specReady: {
    headline: 'Ready to start.',
    subtext: 'Spec ready for review.',
  },
  tasksReady: {
    headline: 'Tasks ready to go!',
    subtext: 'Review and delegate or implement.',
  },
  tasksInProgress: {
    early: {
      headline: 'Making progress.',
      // subtext uses template: `${completed} of ${total} tasks done.`
    },
    mid: {
      headline: 'Things are progressing nicely.',
      // subtext uses template: `We're ${percent}% through the work.`
    },
    late: {
      headline: 'Almost there!',
      // subtext uses template: `${remaining} task${s} remaining.`
    },
  },
  changesUnstaged: {
    // headline uses template: `Review ${count} file change${s}`
    subtext: 'Time to review the changes and push.',
    actionLabel: 'Review changes',
    actionTooltip: 'Opens the changes panel to review, stage, and commit file changes.',
  },
  changesStaged: {
    // headline uses template: `${count} file${s} staged`
    subtext: 'Ready to commit.',
    actionLabel: 'Commit',
    actionTooltip: 'Opens the changes panel to commit your staged changes.',
  },
  commitsUnpushed: {
    // headline uses template: `${count} commit${s} to push`
    subtextNew: 'Push to create a PR.',
    subtextExisting: 'Push to update PR.',
    actionLabelNew: 'Create PR',
    actionLabelExisting: 'Push changes',
    actionTooltip: 'Opens the changes panel to push commits and create a pull request.',
  },
  prOpen: {
    // headline uses template: `PR #${number} open`
    subtext: 'Awaiting review.',
    actionLabel: 'View PR',
    actionTooltip: 'Opens the pull request on GitHub in your browser.',
  },
  prApproved: {
    // headline uses template: `PR #${number} approved`
    subtext: 'Ready to merge.',
    actionLabel: 'Merge PR',
    actionTooltip: 'Opens the pull request on GitHub to merge.',
  },
  allDone: {
    headline: 'All done!',
    subtext: '',
  },
} as const;

export type ProgressCardCopy = typeof progressCardCopy;
