import { parseUiComponentMetadata } from '../component-metadata';
import { spinnerFixtures } from './spinner.fixtures';

export const spinnerMetadata = parseUiComponentMetadata({
  id: 'loading-indicator',
  source: 'src/lib/components/ui/indicators/IntentMarkLoader.svelte',
  publicImport: '$lib/components/ui/indicators',
  legacyImports: [
    '$lib/components/ui/indicators/AgentBadge.svelte',
    '$lib/components/ui/indicators/UnsavedIndicator.svelte',
  ],
  exports: [
    'IntentMarkLoader',
    'AgentBadge',
    'IntentMarkVariant',
    'UnsavedIndicator',
    'intentMarkMotionTiming',
    'intentMarkVariants',
    'spinnerMetadata',
  ],
  category: 'pattern',
  owner: '007-B1',
  callers: [
    'src/features/file-tracking/components/diff/PatchBlockContent.svelte',
    'src/features/layout/components/panel-tabs/Tab.svelte',
    'src/features/log/components/ActivityTimelineItem.svelte',
    'src/features/onboarding/messages/GitHubRepoTab.svelte',
    'src/features/onboarding/messages/ProviderCard.svelte',
    'src/features/onboarding/steps/OnboardingGitHubStep.svelte',
    'src/features/onboarding/steps/OnboardingPromptStep.svelte',
    'src/features/onboarding/steps/OnboardingRequirementsStep.svelte',
    'src/features/workspace/components/WorkspaceActionsMenu.svelte',
    'src/lib/component-catalog/renderers/ContentFieldCatalogPreview.svelte',
    'src/lib/component-catalog/renderers/ScreenStatesCatalogPreview.svelte',
    'src/lib/components/AuggieSetupGate.svelte',
    'src/lib/components/GitHubAuthBanner.svelte',
    'src/lib/components/GitHubAuthModal.svelte',
    'src/lib/components/agent-overview/AgentHierarchyCard.svelte',
    'src/lib/components/agent-overview/AgentHierarchyGraph.svelte',
    'src/lib/components/browser/EmbeddedBrowser.svelte',
    'src/lib/components/chat/AttachmentPreview.svelte',
    'src/lib/components/chat/AutoCommitStatus.svelte',
    'src/lib/components/chat/ChatChangesPanel.svelte',
    'src/lib/components/chat/ChatHeader.svelte',
    'src/lib/components/chat/ChatMessageNavigator.svelte',
    'src/lib/components/chat/ChatPanel.svelte',
    'src/lib/components/chat/LiveStreamPhaseIndicator.svelte',
    'src/lib/components/chat/StreamingTypingIndicator.svelte',
    'src/lib/components/chat/ThinkingBlock.svelte',
    'src/lib/components/chat/ToolStatusIcon.svelte',
    'src/lib/components/chat/TypingIndicator.svelte',
    'src/lib/components/chat/input/ContextPickerButton.svelte',
    'src/lib/components/chat/input/ModelPicker.svelte',
    'src/lib/components/chat/input/ModelPickerOptionItem.svelte',
    'src/lib/components/chat/input/ModelPickerProviderNotice.svelte',
    'src/lib/components/chat/input/SimpleRichInput.svelte',
    'src/lib/components/chat/streaming-status-utils.ts',
    'src/lib/components/code-review/CodeReviewPanel.svelte',
    'src/lib/components/code-review/CodeReviewTabContent.svelte',
    'src/lib/components/code-review/walkthrough/CodeWalkthroughSection.svelte',
    'src/lib/components/code-review/walkthrough/WalkthroughCommentThread.svelte',
    'src/lib/components/code-review/walkthrough/WalkthroughInlineComment.svelte',
    'src/lib/components/code-walkthrough/CodeWalkthrough.svelte',
    'src/lib/components/error/EnhancedErrorBoundary.svelte',
    'src/lib/components/file-explorer/file-explorer-layout.svelte',
    'src/lib/components/file-explorer/file-explorer-sidebar.svelte',
    'src/lib/components/layout/panel-system/LayoutPresetDropdown.svelte',
    'src/lib/components/layout/panel-system/PanelLayoutHeader.svelte',
    'src/lib/components/layout/sidebar-nav/cards/ChiefCard.svelte',
    'src/lib/components/notes/primitives/AgentActionBlock.svelte',
    'src/lib/components/notes/primitives/CliBlock.svelte',
    'src/lib/components/patterns/form/UnsavedIndicator.svelte',
    'src/lib/components/patterns/settings/custom-controls.ts',
    'src/lib/components/terminal/QuakeTerminalOverlay.svelte',
    'src/lib/components/terminal/TerminalSidebar.svelte',
    'src/lib/components/tiptap/TaskNotePreview.svelte',
    'src/lib/components/tiptap/comments/AgentPeekCard.svelte',
    'src/lib/components/ui/SaveIndicator.svelte',
    'src/lib/components/ui/ScrollableSection.svelte',
    'src/lib/components/ui/button/button.svelte',
    'src/lib/components/ui/list/ListItem.svelte',
    'src/lib/components/workspace/CheckoutModePill.svelte',
    'src/lib/components/workspace/CompactWorkspaceInitializer.svelte',
    'src/lib/components/workspace/PullRequestCreator.svelte',
    'src/lib/components/workspace/WorkspaceShellList.svelte',
    'src/lib/components/workspace/WorkspaceSidebarHeader.svelte',
    'src/lib/components/workspace/initializer/BranchSelector.svelte',
    'src/lib/components/workspace/initializer/IssueSuggestions.svelte',
    'src/lib/components/workspace/initializer/RepoAndBranchPicker.svelte',
    'src/lib/components/workspace/initializer/RepoSelector.svelte',
    'src/lib/components/workspace/initializer/SetupScriptAgent.svelte',
    'src/lib/components/workspace/sidebar/CommitDrawer.svelte',
    'src/lib/components/workspace/sidebar/CommitsTimeline.svelte',
    'src/lib/components/workspace/sidebar/DividerButton.svelte',
    'src/lib/components/workspace/sidebar/FileChangesSection.svelte',
    'src/lib/components/workspace/sidebar/MergePanel.svelte',
    'src/lib/components/workspace/sidebar/PRSection.svelte',
    'src/lib/components/workspace/sidebar/PostMergeActions.svelte',
    'src/lib/components/workspace/sidebar/SecondaryRootChangesView.svelte',
    'src/lib/components/workspace/sidebar/WorkspaceProgressCard.svelte',
    'src/lib/components/workspace/sidebar/context-picker/LinearPicker.svelte',
    'src/lib/components/workspace/sidebar/context-picker/SentryPicker.svelte',
    'src/routes/(app)/workspace/creating/+page.svelte',
  ],
  replacement: null,
  characterizationTest: 'src/lib/components/ui/indicators/IntentMarkLoader.test.ts',
  removalGate:
    'Retain IntentMarkLoader as the only indeterminate indicator while canonical callers, deterministic motion tests, and loading catalog coverage pass; AgentBadge and UnsavedIndicator remain internal product exports and are not catalog entries.',
  dynamicImports: [],
  fixtures: spinnerFixtures,
  useWhen: [
    'Use bloom for buttons, list rows, thinking blocks, live-stream phases, typing, hierarchy cards, message navigation, and content previews; streaming status keeps its status-derived bloom, pulse, or twist variant.',
  ],
});
